### ISSUE TITLE
Linking observables

### ISSUE THREAD

**Issue by promontis** [LegendApp/legend-state#101]
Given the following store:

```
store: 
{
   scene: 
   {
      sketch: 
      {
         points: Record<Id, Point>,
         lines: Record<Id, Line> 
      }
   }
}

Line:
{
   start: Point,
   end: Point
}

Point:
{
   x: number,
   y: number
}
```

We can set the same raw object to observables `store.scene.sketch.lines[line.id].start` and to `store.scene.sketch.points[line.start.id]`.

For example:

```
const point = { x: 10, y: 11 }
store.scene.sketch.lines[line.id].start.set(point)
store.scene.sketch.points[line.start.id].set(point)
```

When updating `store.scene.sketch.lines[id].start.set(point)` this will update the underlying raw object. Because `store.scene.sketch.points[line.start.id].set(point)` also refers to the same raw object, it is also updated. All in all, both observables are kept in sync. 

Now, when we observe `store.scene.sketch.lines[line.id].start` by either `observe()` or `onChange()` one would expect to be notified when we update any of the two observables, since they are kept in sync. However, this is only true for when we update `store.scene.sketch.lines[line.id].start` and NOT for `store.scene.sketch.points[line.start.id]`. 

This might not be expected behaviour, thus we propose a method to link two observables, so that when we update one of the two observables, both will be notified because they are linked.

We can link observables by...

1. `link([store.scene.sketch.lines[line.id].start, store.scene.sketch.points[line.start.id]`. 
Note that we can also provide more than two observables in the array

2. `store.scene.sketch.points[line.start.id].set(store.scene.sketch.lines[line.id].start)`. 
So setting one observable with another observable automatically links them together.

**Comment by jmeistrich** [comment]
I think we have a solution for this in version 1.4.0-next.2. 

I've been playing with a few different approaches and found that linking observables directly ended up being confusing and added a lot of complexity around the edges:
- If one is deleted should it delete the links?
- Would we need a way to unlink them?
- Would unlinking them delete the data in one place or just sever the link?
- How would the link be retained after loading back from persistence?
- Data is duplicated into multiple places
- etc...

So the solution I settled on was to enhance `computed` to be able to link to another observable, and create a new `proxy` that returns a computed given a key. This way the data itself is only in one place and links take you to the original node.

So in the upcoming 1.4.0 there's three changes to support this:
1. Returning an `observable` in a `computed` creates a two-way link
2. `proxy` creates a proxy object that returns a computed for a given key
3. `computed` and `proxy` are supported in the initialization object in an observable

So using that I think the above example could be solved something like this:

```js
import { observable, proxy } from “@legendapp/state”;

const store = observable({
  scene: {
    sketch: {
      points: {},
      lines: {},
      lineStart: proxy((lineID) => 
	store.scene.sketch.points[store.scene.sketch.lines[line.id].start.get()],
      lineEnd: proxy((lineID) => 
	store.scene.sketch.points[store.scene.sketch.lines[line.id].end.get()]
    }
  }
})

// Listen to these for changes to the line’s start and end points
const lineStart = store.scene.sketch.lineStart[line.id]
const lineEnd = store.scene.sketch.lineEnd[line.id]

// Setting the point at the start id would notify the listener to lineStart
const point = { x: 10, y: 11 }
store.scene.sketch.points[line.start.id].set(point)
```

What do you think? Does this seem like a good approach to the original problem? Any ideas for how to do it better?

**Comment by jmeistrich** [comment]
I'm going to close this since it is released now. Please let me know if the current implementation doesn't quite solve it for you.
