### ISSUE TITLE
Improvements to `useFetch` hook

### ISSUE THREAD

**Issue by matthewmturner** [LegendApp/legend-state#102]
There might also be some value in creating an LS hook that does some of the basics that people use RQ for? I just added a `useFetch` hook in `0.21.6` that just wraps around the lifecycle of the promise and exposes `{ data, error, loading }` as an observable, which works like this:

```jsx
const obsData = useFetch<{ fact: string }>('https://catfact.ninja/fact');

return <div>{obsData.data.fact}</div>
```

Maybe a hook with a few more features like retries and mutations could be a useful minimal alternative to RQ? Of course I'm definitely not trying to go too deep on that - RQ does a whole lot! But since we already have the local state and caching covered, it could be useful? If that seems like a good idea, let's start a new thread for it? I don't want to take this RQ thread too off topic.

_Originally posted by @jmeistrich in https://github.com/LegendApp/legend-state/issues/48#issuecomment-1294786688_

**Comment by matthewmturner** [comment]
Could use this as a tracker issue. The first thing that comes to my mind to add is pagination.

- [ ] Pagination

**Comment by jmeistrich** [comment]
I use firebase for everything myself so I don't have much expertise in the area. Would you like to take the lead on this and I can advise/review?

**Comment by matthewmturner** [comment]
Yup works for me

**Comment by jmeistrich** [comment]
I believe all of this is now solved in version 3. Have you had a chance to try it @matthewmturner? I’ll close this issue since I think it’s done, but please let me know if you want any further improvements.

https://legendapp.com/open-source/state/v3/sync/persist-sync/
