### ISSUE TITLE
Can't set observable to null when it's value is 0

### ISSUE THREAD

**Issue by rikjke** [LegendApp/legend-state#106]
I have type number | null for observable, it's state doesn't change from number to null if the previous value is 0

**Comment by GiFarina** [comment]
version? or repro?
I can't reproduce in version "@legendapp/state": "^1.0.0-rc.13",
<img width="117" alt="Screenshot 2023-03-01 at 22 22 39" src="https://user-images.githubusercontent.com/50060506/222306476-def10f35-df2f-4685-a1fa-a38cb876e3c3.png">

**Comment by jmeistrich** [comment]
I added a test to make sure and it seems to work correctly: https://github.com/LegendApp/legend-state/blob/persist/tests/tests.test.ts#L473

@rikjke Can you share a code snippet that shows the incorrect behavior?

**Comment by rikjke** [comment]
My bad, I had an old version. Works fine with "^1.0.0-rc.13". Great lib though!
