### ISSUE TITLE
`If` in `Show` component isnt triggered by truthy values

### ISSUE THREAD

**Issue by matthewmturner** [LegendApp/legend-state#107]
Such as `[]` and `error` also isnt triggered when it is present in a `observableFetch` response (you have to use `errorStr`)

**Comment by jmeistrich** [comment]
That had made sense to us at the time in the context of our apps (like Show a list of clients with a fallback message if the list is empty) but it's obviously not the expected general purpose behavior. So we're changing the default behavior of the `if` prop to be a regular truthy check and adding an `ifReady` prop which checks that an object has keys or that an array has values (the previous `if` behavior).

It's updated in the latest RC.
