### ISSUE TITLE
NextJs 12 Dom Not updating problem.

### ISSUE THREAD

**Issue by emrahc** [LegendApp/legend-state#110]
I have nextjs 12 application. I have faced with 3 problems.

1) When i use enableLegendState() dom is not updating itself

2)When i wrap component with observer() component rerenders.

3)Once i managed to work it but then complicated object didnt update

Basic example 

Problem 
1)Value doesnt update 

```
enableLegendState()
const App =()=>{

count =useObservable(0)

return
(
<>
 <h1>count:{count.get}</h1>
<btn onClick={()=> count.set(count.get()+1)}>add 1 </btn>
</>
)
}

```

Problem 
2) Value updates but rerenders

```
const App =observer(function App()=>{

count =useObservable(0)

return
(
<>
 <h1>count:{count.get}</h1>
<btn onClick={()=> count.set(count.get()+1)}>add 1 </btn>
</>
)
})

```

Problem 3 I have complicated form. When user types i update whole object but it doesnt update dom. It happened once. I dont know how to repeat it.

Thanks

**Comment by matthewmturner** [comment]
When you call `count.get` in the header it should be `count.get()` in order to properly track, I believe

**Comment by jmeistrich** [comment]
Yes that's right . `count.get` is a function so you need to call it. `count.get()` renders the raw value, and you need `observer(...)` to make the component track calls to `get()`.

Alternatively you can render the observable itself like `<h1>count:{count}</h1>`. That will make that element auto-track count, and you don't need observer.

**Comment by emrahc** [comment]
Thank you for swift answers.  Now i am having the problem 3. 

I have an object  I use it for form component

```
const formValue = useObservable({});

return(

    <div>
      render:{renderCount}
      count:{count}
      Form Object 1:{JSON.stringify(formValue.get())}
      Form Object 2:{JSON.stringify(formValue)}

      <Form
        formData={formValue}
        schema={uygunsuzlukSchema}
        uiSchema={uygunsuzlukUi}
        validator={validator}
        onSubmit={onSubmit}
        onChange={_onChange}
      />

</div>

```

Count updates itself without rerender works. When i change the formValue object it doesnt update the dom. But i see changed values in console.log(). I passed both formValue and formValue.get().  

Thanks

**Comment by jmeistrich** [comment]
In this case the component would need to be an observer so that it can track changes when you call get().

**Comment by emrahc** [comment]
I wrapped main component with observer. Formdata updated but triggered rerender. When i update count it doesn't rerender the component. Thanks

**Comment by jmeistrich** [comment]
Can you share the full source or ideally a codesanbox? I don't see anything wrong in that snippet.

**Comment by jmeistrich** [comment]
I'm going to close this due to inactivity. @emrahc If this is still an issue please let me know.
