### ISSUE TITLE
event parameter in useObserve callback is not populated

### ISSUE THREAD

**Issue by SMhdAsadi** [LegendApp/legend-state#113]
I want to do something based on an observable change in a component. I need to check the previous value of the observable and compare it to the current value. How to do this?

Currently I can see useObserve hook takes a callback, which receives a parameter `e`. This `e` parameter has `value` and `previous` properties (which I think are useful for my needs) but these are always undefined. Is it a bug or something?

**Comment by jmeistrich** [comment]
Oh hmm, there was a bug in how previous was calculated - we originally intended it to be used internally just for comparison but then exposed it in the event without fixing it for that usage. And we need to update the docs for observe/useObserve. We'll do that soon! But I'll just explain it here:

observe/useObserve take a Selector as the first parameter, which is either an Observable or a function. The value of that Observable or the return value of the function is passed in as `value` to the second parameter, the reaction. And `previous` contains the previous `value`  from the previous time the reaction was called. 

Here's a sandbox showing it, using the latest version with the bug fixed: `1.0.0-rc.29`

Please let me know if that's still not working right, and thanks for the report!

**Comment by SMhdAsadi** [comment]
Tested version `1.0.0-rc.20` and `previous` is working as expected. Thanks.
