### ISSUE TITLE
Inserting elements in the middle of an array doesn't work

### ISSUE THREAD

**Issue by Pajn** [LegendApp/legend-state#12]
Using for example splice to insert an element in the middle of an array cases its and consecutive bindings to break/refer to the wrong element.

Sandbox:
https://codesandbox.io/s/legend-w-observable-forked-5s88ge?file=/src/App.tsx

Click the plus 3-4 times. Each time a new item gets inserted in the middle with a label of the total count.
Expected output after four clicks:
- item 1
- item 3
- item 4
- item 2

Actual output:
- item 1
- item 2
- item 2
- item 2

Now press the rerender button to see the JSON output the actual value (which has updated correctly)

**Comment by jmeistrich** [comment]
Thanks, that definitely looks like a bug. It's late night here so I'll fix it and release an update tomorrow.

**Comment by jmeistrich** [comment]
This should be fixed in 0.18.7, but please let me know if it's still not working or you have any other issues.

**Comment by Pajn** [comment]
I still get the same issue in my app :/ In the sandbox above, changing version to 0.18.7 works for the first four items but then item 4 gets duplicated in the same way item 2 was previously so it ends up like this:
- item 1
- item 3
- item 4
- item 4
- item 4
- item 2

**Comment by jmeistrich** [comment]
Ok, thanks for bearing with me! It seems to be actually fixed now :)

**Comment by Pajn** [comment]
🥳 Seems to work now :)
