### ISSUE TITLE
Issue with useObserve and optional props

### ISSUE THREAD

**Issue by AradSharafi** [LegendApp/legend-state#120]
Hi,

I found an issue while using the useObserve hook. The hook takes two parameters, a selector and a callback. However, I noticed that when I have an observable that comes from an optional prop that can be undefined, I get an error stating that it must be an observable and not undefined.

I'm not sure if this is expected behavior or a bug, but it would be helpful to have a solution for this situation. Can you provide any guidance on how to handle this?

Thanks.

Here's an example: 

```tsx
interface PropTypes {
  value?: ObservablePrimitive<boolean>;
}

function MyComponent(props: PropTypes) {

  useObserve(props.value , () => {
    ...
  })

  return (
    ...
  )
}
```

**Comment by matthewmturner** [comment]
@jmeistrich in the latest does that mean if an observable is provided as a parameter and a different observable is accessed in the callback that it only rerenders if the observable parameter changes and not if the other observable changes?

**Comment by jmeistrich** [comment]
@matthewmturner `observe`/`useObserve` has two parameters - `selector` and `reaction`. `selector` runs in a tracking context and it re-runs when those observables change. `reaction` does not run in a tracking context so nothing accessed there will affect anything. It's meant to be used for setting things whenever the first parameter changes. If you want the reaction to also track you probably want to just use the one parameter with the second part inside an `if`.

```js
observe(() => {
   if (obs.get()) {
      // Do the reaction here
   }
})
```

**Comment by jmeistrich** [comment]
I'm closing this since the updated documentation explains the distinction better. Please feel free to reopen this or even submit a PR if you think the docs should be improved further.
