### ISSUE TITLE
Remove Next 12 as Peer Dep

### ISSUE THREAD

**Issue by 10thfloor** [LegendApp/legend-state#128]
Getting an error in my Next 13 app:

**Could not resolve dependency:**
npm ERR! peer next@"^12" from @legendapp/state@1.2.3

Why should NextJS be a peer-dep?

**Comment by jmeistrich** [comment]
Ah, looks like I forgot to make next an optional peerDependency. There's a (not yet documented) helper hook for routing in Next, useObservableNextRouter, so we have the peerDependency just for that.

In version 1.2.5 I've marked it as optional and fixed the semver so 13 would work. Please let me know if that fixes it for you. Thanks!

**Comment by 10thfloor** [comment]
Yes it does! Thank you very much.
