### ISSUE TITLE
Hooks docs a little confusing.

### ISSUE THREAD

**Issue by GollyJer** [LegendApp/legend-state#135]
Hi. I just wanted to point out that the examples in the [docs for Hooks](https://legendapp.com/open-source/state/hooks/) don't work.

It took me searching until I figured out the components need to be wrapped in `observer` to work.

**Comment by jmeistrich** [comment]
Yes, great point! We're about to release version 1.3.0 and will fix those docs pages along with that update.

**Comment by jmeistrich** [comment]
FYI we just updated those docs.
