### ISSUE TITLE
Why useSelector triggers a new render when the observable value didn't changed?

### ISSUE THREAD

**Issue by SMhdAsadi** [LegendApp/legend-state#137]
### Description
When I use the `useSelector` hook with an observable, it causes a new render whenever I set something to that observable, no matter the value has changed or not. This behavior can cause infinite re-renders easily. I have to fallback to useState because of this issue.

### Example code
```tsx
function ExampleComponent() {
  const obs = useObservable(false);
  const val = useSelector(obs);

  console.log('render');

  return <Button title='press' onPress={() => obs.set(false)} />;
}
```
consider this simple example. Render this component somewhere and press the button. Each press logs a new 'render'. Why is that?

### Versions
React Native: 0.71.8
Legend-State: 1.3.5

**Comment by jmeistrich** [comment]
Ah, there was a little bug there - primitives were not checking the previous value before notifying. I just released 1.3.6 to fix it.
