### ISSUE TITLE
[remote persistence plugin] Supabase

### ISSUE THREAD

**Issue by rickylabs** [LegendApp/legend-state#139]
I love the idea to implement a remote persistence system directly into a state manager, well done !

Any plans to implement Supabase anytime soon ? Since it's open source and quite widely used I think it would be nice to have it as a new plugin !

**Comment by jmeistrich** [comment]
I think Supabase will be the first one to tackle after we finish the Firebase Realtime Database one that we're working on now. It does look very good and it's getting quite popular!

**Comment by rickylabs** [comment]
Any news on this?

**Comment by jmeistrich** [comment]
I just released 3.0 alpha which has a new sync system and a Supabase plugin 🎉

New sync docs: https://legendapp.com/open-source/state/v3/sync/persist-sync/
Supabase plugin docs: https://legendapp.com/open-source/state/v3/sync/supabase/

Please let me know if it needs any improvements!
