### ISSUE TITLE
Enhance when function for React components

### ISSUE THREAD

**Issue by SMhdAsadi** [LegendApp/legend-state#140]
## Description:
The current implementation of the `when` function poses a limitation when used directly inside React components. A new `when` function is called after each render, leading to undesired behavior.

## Suggestion:
Introduce a specialized hook called `useWhen` for React components. This hook would optimize the `when` function's logic for React's rendering cycle, preventing unnecessary re-calls and improving efficiency.

**Comment by jmeistrich** [comment]
Ah that's an interesting idea! Can you share an example of how you'd want to use it?

You might be able to just run when after mount?

```js
useMount(() => {
   when(value$, () => {})
})
```

**Comment by SMhdAsadi** [comment]
Sure. I have implemented an observable that stores the netInfo object and updates whenever there are changes in the network status. My goal is to perform certain tasks when the internet is accessible.
To achieve this, I am using the `useObserve` hook with the netInfo observable. At the end of the `useObserve` block, I cancel the observation manually.

Yeah your approach works great. It would be beneficial to create a custom hook that encapsulates this functionality and can be reused in different parts of the codebase. It could be a good addition to the toolbox this library gives us.

**Comment by jmeistrich** [comment]
We've added this for version 2.0. You can use it now if you install the @beta version, or it will be coming in the full 2.0 release. Thanks for the suggestion!
