### ISSUE TITLE
computed added in observable latter doesn't seem to track

### ISSUE THREAD

**Issue by mathieucivel** [LegendApp/legend-state#147]
When adding a computed in an existing observable, I expected the same behaviour than creating an observable with a computed.

https://codesandbox.io/s/sandpack-project-forked-pnggt4?file=/App.js 

Not sure if it is intended or logical. Sorry for the noise if that is the case.

**Comment by jmeistrich** [comment]
Hi @mathieucivel! There's a couple issues in your example:

1. You're creating observables directly in a React component, which will create brand new observables every time it runs. You can use `useObservable` and `useComputed` or move them out of the component.
2. The component is not observing changes, so it will not re-render when it changes. You can wrap the component in `observer` to make it track `get()` calls and update when they change.

I made a little fork of your example that does track correctly: https://codesandbox.io/s/sandpack-project-forked-wnqtzt

But to your main point:

Legend-State doesn't support setting or assigning computed values - they're only extracted within the constructor. Although it could be fairly easy to support the simple cases you've shown, there are more complex cases that would cause problems. The main problems are:

1. Supporting computeds assigned deep in a hierarchy would require processing all hierarchy of incoming sets. We currently optimize setting to only processed children that have changed from the previous value. To support this we'd have to remove those optimizations, which could slow all sets. As an example:
```js
state.set({
  child: {
    grandchild: {
      tinybaby: computed(...)
    }
  }
})
```

2. What would it mean to set a computed over a previous computed? Would it delete the old one and replace it with the new one? Or should it somehow replace the compute function of the original one? If so, should it update immediately? What would happen to the listeners of the previous computed? You may want to keep them if the computed is basically the same but if it's totally different the original listeners would probably not want the new value. We could throw an error if overwriting a computed, but that might not be great either. There's a lot of strange edge cases there that get confusing... 
```js
const state = observable({
  compy: computed(() => A + B)
})
state.set({
  compy: computed(() => C + D)
})
```

We haven't been able to think of any scenarios where it would be important to add them later, so at least for now we're requiring they be created in the constructor. Do you have some scenarios where it would be important for you? If so we may want to rethink this and try to find a good solution.

**Comment by mathieucivel** [comment]
Thank you for taking the time to answer. And thanks for pointing the issues of the example, that confirmed my understanding (I've latter tried to move the state initialisation outside the component and the effect was the same. As the component was intended to be rendered once I've just let the example as is).

I don't have a strong scenario where computed needs to be added or updated dynamically. In my case I can create computed before creating an observable.
