### ISSUE TITLE
`persistObservable` doesn't work for primitive types

### ISSUE THREAD

**Issue by todorone** [LegendApp/legend-state#15]
`persistObservable` works if observable is `object` type only, but it will be very handy to use it for `string`, `number` and `boolean` observables

**Comment by chakrihacker** [comment]
@todorone Which version are you using??

**Comment by todorone** [comment]
> @todorone Which version are you using??
> 
> Also are you using in React or React Native??

Latest version - `0.18.8`
I use React

**Comment by jmeistrich** [comment]
Cool, this should be pretty easily doable. I'll try to get to it soon.

**Comment by jmeistrich** [comment]
Fixed in 0.19.5, but please let me know if there's any more issues with it.

**Comment by todorone** [comment]
@jmeistrich works like a charm, thanks.
