### ISSUE TITLE
 Cannot read properties of undefined (reading 'Name')

### ISSUE THREAD

**Issue by daehaha** [LegendApp/legend-state#159]
App.tsx
```
const state$ = observable({ roomName: "office" })
<ChoiceRoom next={next} prev={prev} platform='ustory' roomName={state$.roomName} />];
```
ChoiceRoom.tsx

```
interface ChoiceRoomProp {
	roomName: ObservableObject;
}
const ChoiceRoom = ({ platform, next, prev, roomName, change }: ChoiceRoomProp) => {
roomName.set(room.name)
}
```
currently I'm using vite with react. and this work correctly sending as prop to child component 

however it doesn't work only say Cannot read properties of undefined 

App.tsx

`const state$ = observable({ Name: "office", Link: "www.daum.net" })`

ChoiceRoom.tsx

```
interface ChoiceRoomProp {
	platform: string;
	next: () => void;
	prev: () => void;
	room$: ObservableObject<{ Name: string, Link: string }>;
	change: () => void;
}

const ChoiceRoom = ({ platform, next, prev, room$, change }: ChoiceRoomProp) => {
room$.Name.set()}

``` 

how to solve it?

**Comment by jmeistrich** [comment]
It's little bit hard to tell with how the code is formatted, and I'm not sure why App and ChoiceRoom changed so significantly between examples. Is it working correctly in the first example but not the second? In the second it looks like you're not actually setting Name to anything? There's no parameter passed into `room$.Name.set()`.

If that doesn't solve it can you share more of the actual code and the full error with stack trace?

**Comment by jmeistrich** [comment]
I'm going to close this due to inactivity. Feel free to re-open it and share some code to help track down an issue.
