### ISSUE TITLE
opaqueObject() seems to be broken in Vite React TS + SWC

### ISSUE THREAD

**Issue by jaekwak02** [LegendApp/legend-state#163]
Observable does not seem to respect opaqueObject() at all in the latest version (1.6.4). This example does not work and logs a hundred errors to the console about circular references.

```
import { observable. opaqueObject } from '@legendapp/state'

const state$ = observable({ text: 'hi', body: opaqueObject(document.body) })
```

I tested this in a new Vite React TS + SWC project.

**Comment by jmeistrich** [comment]
Thanks for finding that! opaqueObject was not preventing traversal in the constructor when looking for computeds. Fixed in 1.7.2
