### ISSUE TITLE
how to sync state via import?

### ISSUE THREAD

**Issue by lawplatform** [LegendApp/legend-state#165]
I'm follwe the examplet to test global state 
however state value not shared what I expected 

state value exactly same the tutorial 
```
import { observable } from '@legendapp/state'
import { persistObservable } from '@legendapp/state/persist'
import { ObservablePersistLocalStorage } from '@legendapp/state/persist-plugins/local-storage'

export const State = observable({
	settings: {
		showSidebar: false
	},

})

persistObservable(State, {
	local: 'example',
	persistLocal: ObservablePersistLocalStorage,
})
```

how ever It can't not changed then I expecd
I want shared value change when I press the button. but nothing happens 
```
function App() {

	return (
		<>
			<div>this is legend test</div>
			<Child></Child>
			<div>----</div>
			<Child_Two></Child_Two>
		</>
	)
}

export const Child = () => {
	const click = () => {
		State.settings.showSidebar.set(true)
		console.log(State.settings.showSidebar.get());

	}
	return (
		<div>{State.settings.showSidebar.get() ? "hello" : "no"}
			<button onClick={click}> click </button>
		</div>
	)
}
```

but  div message on clid component almost same thing ans I expected it change the value but noting chianged..

my source code is here 
https://github.com/lawplatform/legendStudy

**Comment by jmeistrich** [comment]
Hi @lawplatform,

The problem you're having there is that Child is not observing the changes in showSidebar. `get()` by itself returns the value but does not subscribe. If run in an [observing context](https://legendapp.com/open-source/state/reactivity/#observing-contexts) then it will trigger an update in the observing context. 

You could make Child an observing context by wrapping it in [observer](https://legendapp.com/open-source/state/react-api/#observer-hoc).

Or easier than that, change the `get()` while rendering Child to `use()` and it will subscribe itself. That just needs [a bit of setup](https://legendapp.com/open-source/state/react-introduction/).

And may I ask which example you based off of? I think we may need to clarify this in the docs better.

**Comment by lawplatform** [comment]
thanks! it solved :)
