### ISSUE TITLE
Document reliance on internals

### ISSUE THREAD

**Issue by gaearon** [LegendApp/legend-state#17]
This library appears to significantly depend on React internals which aren't bound by semver.

I think it would be fair to add a notice that by taking it on as a dependency, you're making every React upgrade risky, and at some point might not be able to upgrade at all.

**Comment by jmeistrich** [comment]
As of 0.19.0 we've deprecated usage of internals and we will remove it completely in the next version.

Thanks for your feedback @gaearon!
