### ISSUE TITLE
nest observable do not trigger onChange

### ISSUE THREAD

**Issue by lake2** [LegendApp/legend-state#176]
```tsx
const loading = () => {
    var state = observable({
        value: false,
        number: computed((): string => {
            return `${state.value.get() ? 1 : 0}`;
        }),
        start() {
            state.value.set(true);
        },
        stop() {
            state.value.set(false);
        },
    });
    return state;
};

const store = observable({
    loading: loading(),
});

store.loading.onChange(
    ({ value }) => {
        console.log('========onchange', value);  // do not print
    },
);

store.loading.start()
```

**Comment by jmeistrich** [comment]
Nested observables is not currently supported. We actually are experimenting with it in the `computed` branch in version 1.9.0-next.2, but so far it's just a prototype of nesting computeds that isn't 100% there. And we're not sure of the implications of having a computed/observable nested into multiple outer observables, so we're not sure how safe it would be and may end up not moving forward with it.

May I ask what you're trying to do though? Although we've thought of a few use cases for nesting computeds inside an observable, I'm not sure what would be the benefit of nesting observables.

**Comment by lake2** [comment]
> Nested observables is not currently supported. We actually are experimenting with it in the `computed` branch in version 1.9.0-next.2, but so far it's just a prototype of nesting computeds that isn't 100% there. And we're not sure of the implications of having a computed/observable nested into multiple outer observables, so we're not sure how safe it would be and may end up not moving forward with it.
> 
> May I ask what you're trying to do though? Although we've thought of a few use cases for nesting computeds inside an observable, I'm not sure what would be the benefit of nesting observables.

I want to create a reusable state, which may be called an 'atom' in jotai.
For instance, I can use the common loading state in different stores.

const loading = () => {
    var state = observable({
        value: false,
        number: computed((): string => {
            return `${state.value.get() ? 1 : 0}`;
        }),
        start() {
            state.value.set(true);
        },
        stop() {
            state.value.set(false);
        },
    });
    return state;
};

const store_1 = observable({
    loading: loading(),
});

const store_2 = observable({
    loading: loading(),
});

**Comment by jmeistrich** [comment]
Oh in that case I would suggest just making loading a separate store. It shouldn't need to be included in both - you could just import it separately from anywhere you want to use it?
