### ISSUE TITLE
UI toggle via legend state? 

### ISSUE THREAD

**Issue by lawplatform** [LegendApp/legend-state#184]
I want to create a simple modal using the 'legend-state'. 
My intention is straightforward: 
when the button is clicked, the 'show$' state changes and the div window is displayed

So I made this code 
```
const view$ = observable(false);
const toggleShow = async () => {
		view$.set(!view$.get());
}
return(
<button onClick={toggleShow} className="btn btn-neutral"> show ? </button>
	{view$.get() ? <div> canyou see</div> : <div>nope</div>}
)
```

but I found code not work in return `<div>` tag 
`{view$.get() ? <div> canyou see</div> : <div>nope</div>}`

but I found state suceffully changed.
only not affected div state  
how to apply change state in the conditional div part ?

**Comment by lawplatform** [comment]
I'm sorry not to see the document of react part! 
using <show> tag for the conditional state work out of box :)

```
<Show if={view$}>
{() => <Card_AB />}
</Show>
```

**Comment by jmeistrich** [comment]
Haha good to see you self-solved it :). Do you think there's something we should do to improve the documentation to make it more obvious?

By the way, an easier way to set an observable based on a previous value is by using `set` with a function that gets the previous value, like React does in useState:
```js
const toggleShow =() => {
	view$.set(v => !v);
}
```

Or even easier, booleans have a helper `toggle` function so you could just pass that to onClick:

```jsx
<button onClick={view$.toggle} ...
```
