### ISSUE TITLE
Ts Problem on computed fn

### ISSUE THREAD

**Issue by Barna-Molnar** [LegendApp/legend-state#195]
hi, 

I am having currently a couple of issues, I have copied the code from the docu and pasted it, but I am getting Ts problem though...
first, it says it is a string

![from docu](https://github.com/LegendApp/legend-state/assets/72700492/dbc7a0f9-d5b1-494d-839c-b527d394b884)

I hovered over the fullName prop to see what was inferred by ts: 
![prop type inference](https://github.com/LegendApp/legend-state/assets/72700492/e57b6a5e-c076-42fd-80b7-8e5cb1b54b19)

then I have changed to match the type: 
![with Basefn type](https://github.com/LegendApp/legend-state/assets/72700492/2ce6a5de-9789-4cda-9e78-aa2370185d80)

tried with the computed one as well 
![after change type to match infered type](https://github.com/LegendApp/legend-state/assets/72700492/2817b58f-1aae-4fde-9ee1-97325d5f2667)

after that, it is still a string :S then I have changed to string : 
![after change to string ](https://github.com/LegendApp/legend-state/assets/72700492/ecee3415-0b96-4d72-8b90-19237533f587)

and after that it says, that it is not okay 'cos string can not be Observablecomputed<string>

do you have any idea what I am doing wrong ?? 

And to be honest the docu is not detailed enough to get a good picture of how this should work, although I have to admit that I am totally new to legend state but it looks great and I would like to use it in production.
Any suggestion would be appreciated.

Warm Regards

**Comment by jmeistrich** [comment]
It should be `computed((): string => {`. I'll fix the mistake in the docs. It should be typed as an observable only if it links to a different observable, and I changed that last minute while writing the docs and forgot about the distinction 🤦.

It looks like there is a bug with the type of the outer observable when it has a computed child. It's currently coming out as:

```ts
const state$: ObservableObject<{
    fname: string;
    lname: string;
    setName: (name: string) => void;
    fullname: ObservableComputed<string>;
}>
```

But `fullname` should be of type `string`. I'll look into that and try to fix it soon.

**Comment by Barna-Molnar** [comment]
Thanks for inviting me to the Slack Channel.
I will test a couple of things in the following days, and weeks and if anything comes up I will report it either here in this issues section or maybe first ask in Slack channel. I am to this style, and if I can contribute somehow, extend docu, or put in some help to make code better I will readily do it! 
I will check this issue further and how we can work around it. if you have found already the/ any solution just please ping me.
thanks

**Comment by jmeistrich** [comment]
I think this should be fixed in version 3 as `compupted` is no longer a separate thing. But please let me know if you still see any issues.
