### ISSUE TITLE
Should react not be an optional peer dependency?

### ISSUE THREAD

**Issue by briandipalma** [LegendApp/legend-state#209]
Upgraded one of our components to legend-state and gutted to find out that the tests won't load because of missing "react" module. I'm using pnpm in a workspace and I think the issue is that the package.json doesn't specify a dependency on react. So pnpm (correctly) doesn't create a symlink in the top level/root workspace `node_modules` directory. You can't import react in your code and not declare it as some sort of dependency?

**Comment by briandipalma** [comment]
Possibly use the lowest version of react that legend-state works on? React 16?

**Comment by jmeistrich** [comment]
Are the tests importing from "@legendapp/state/react"? I had thought that if you just import the core "@legendapp/state" it would be fine without having react installed, though maybe I missed something or it's different with pnpm somehow?

**Comment by briandipalma** [comment]
https://github.com/pmndrs/zustand/discussions/407 I'll see if I can make pnpm install react into the legend-state node_modules it creates but I'm not pretty sure that this is something legend-state should declare itself.

**Comment by jmeistrich** [comment]
We used to have it in peerDependencies but removed it because it was causing issues in some environments: https://github.com/LegendApp/legend-state/blob/ad267ac5f4cb30b8d3869351101f61eeb9997a1a/CHANGELOG.md?plain=1#L183

Unfortunately I don't remember what the issues were... Maybe we should add it back now and see if anyone complains 😂

Could you try patching our package.json to add the peerDependencies with https://github.com/ds300/patch-package/ and see if that fixes it?

I am surprised though: if your tests have react in the package then why is Legend-State erroring on the import? It should be in the node_modules? so it should see it Or does pnpm require it to be in peerDependencies to see it somehow? I had thought peerDependencies was merely a hint that those packages need to be installed alongside?

**Comment by briandipalma** [comment]
pnpm workspaces are strict. They create a new, flat, folder structure that replicates what the package.json says at the root of the workspace (inside `$ROOT/node_modules/.pnpm`) and creates symlinks to that structure from each packages node_modules. That's what you see in the screenshot.

So if legend-state doesn't mention react then it won't create a symlink inside its node_modules. That's totally correct. 

When Webpack loads legend-state and legend-state says `import "react"` it works its way up and doesn't find the dependency. I can't see an easy way to force pnpm to just add a dependency. That package you linked only works for npm and yarn. I can't find why you had issues with react as a peer dependency before but I'm quite sure that's it's correct to declare react as an optional peer dependency.

Nothing pnpm or Webpack are doing is wrong. It's just pnpm workspaces are (painfully) strict and correct. With local npm/yarn this would just work as long as you install react in your local package. But workspaces move everything out of your local node_modules and use symlinks based on what you declare in your package.json.

**Comment by briandipalma** [comment]
My local package just contains a symlink to the structure created at the root of the workspace:

![image](https://github.com/LegendApp/legend-state/assets/1597820/fc76897a-c987-4a12-93bd-ea4ea97f895c)

**Comment by briandipalma** [comment]
I don't mind helping fix the optional peer dependency issues if you see them again. Although I don't understand what they could be. You are declaring something an optional peer dependency so I don't see how that could cause failures.

**Comment by briandipalma** [comment]
```
    "peerDependencies": {
        "react": ">=16.8",
    },
    "peerDependenciesMeta": {
        "react": {
            "optional": true
        }
    },
```

Should fix the issue for us as we only use react.

**Comment by briandipalma** [comment]
https://pnpm.io/symlinked-node-modules-structure

```
A great bonus of this layout is that only packages that are really in the dependencies are accessible. With a flattened node_modules structure, all hoisted packages are accessible. To read more about why this is an advantage, see "[pnpm's strictness helps to avoid silly bugs](https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html)"
```

I can workaround this issue by adding react as a root workspace dependency or hoisting react in the `.npmrc` file but it's far from ideal.

**Comment by jmeistrich** [comment]
Ok great! I agree that it seems more correct to add it. It may be that whatever the issue was previously has been fixed by now or was caused by something else. I'll add it in the next update.

**Comment by briandipalma** [comment]
Fixed. Thanks!
