### ISSUE TITLE
Migrate @tanstack/react-query to v5

### ISSUE THREAD

**Issue by beautyfree** [LegendApp/legend-state#210]
https://tanstack.com/query/latest/docs/react/guides/migrating-to-v5

**Comment by MohammadrezaShad** [comment]
when use useObservableQuery I will be encountered queryClient.defaultQueryOptions is not a function error

**Comment by jmeistrich** [comment]
Would somebody be able to submit a PR to migrate it? I'm currently quite swamped with a big project to improve computed and persistence, and I don't use Query myself so it's a bit tough for me to test it correctly.

I think we should have plugins for both v4 and v5 to maintain compatibility?

We're planning to deprecate `useObservableQuery` soon to favor the `persistPluginQuery` persistence plugin, so let's focus the efforts on upgrading `persistPluginQuery`.

**Comment by kylegillen** [comment]
Any progress on this? Would be really great to see this added.

**Comment by jmeistrich** [comment]
Thanks for the bump! I've been focused on getting the 3.0 update ready so I haven't had a chance to dig into the PR yet. I just replied to it - basically I'm concerned about breaking users of v4 by using v5 APIs, so if we can clear that up I'm very happy to merge it :)

**Comment by jmeistrich** [comment]
I just released version 3.0 alpha which has a new much better sync system which may fully solve remote sync so you don’t need Query. And it also includes a new Query plugin, and set it up to work with Query v5. See:

Docs of the new sync system: https://legendapp.com/open-source/state/v3/sync/persist-sync
Docs of the Query plugin: https://legendapp.com/open-source/state/v3/sync/tanstack-query/

Does that work well for you? Please let me know if it needs any futher improvements.
