### ISSUE TITLE
Type error in nextjs when using a persistent observable

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [LegendApp/legend-state#211]
This code below results in this error: 
![image](https://github.com/LegendApp/legend-state/assets/77451351/3c958baf-56f6-4f2c-9433-361950811619)

```typescript
export const activeCity$ = observable<ICity>({
  id: 1,
  name: "",
  coord: { lat: 0, lon: 0 },
  state: "",
  country: "",
});

persistObservable<ICity>(activeCity$, {
  local: "activeCity",
  pluginLocal: ObservablePersistLocalStorage,
});
```

**Comment by jmeistrich** [comment]
The problem is that when you persist an observable it creates a `state` property on it with its sync state. But that seems to break down when persisting a city 😂.

You can fix it by renaming `state` to something else. We'll put in better error handling to throw a better warning if your observable contains a key named `state`.

**Comment by FleetAdmiralJakob** [comment]
OH MY GODDD, WHAT THE HELL!

THANK YOU SO MUCH! 

I hope you guys can fix it!

**Comment by FleetAdmiralJakob** [comment]
The problem is that my huuuuge json uses this property and I don't want to change it

**Comment by FleetAdmiralJakob** [comment]
Can you say why this is a problem since I updated to v2? Before I didn't have the problem. Maybe there is the bug in a change that was made 🤔

**Comment by jmeistrich** [comment]
There was a breaking change in v2: https://legendapp.com/open-source/state/other/migrating/#promise-behavior-changed. It was described as being about promises but we should clarify that it's about persisting too (we aligned their behavior for consistency).

I think we should change the property to be named `_state` instead to not conflict with user types. We'll change it to add a _state key and have it work for both, then we'll deprecate `state` soon. I'll release an update shortly after testing a bit to make sure it doesn't break anything.

**Comment by FleetAdmiralJakob** [comment]
Thank you so much!

**Comment by jmeistrich** [comment]
Version 2.0.2 should have fixed this - it added `_state` and stopped crashing if `state` was already defined. But let me know if there's still any issues!
