### ISSUE TITLE
Putting an observable in an observable store 

### ISSUE THREAD

**Issue by briandipalma** [LegendApp/legend-state#214]
If you put an observable in your store it gets wrapped in an observable. That means you have to write get() twice to get the actual value, like so:

```typescript
  console.log("First update", store.account.get().get());
```

Honestly I've no idea if this is a bug...what happens if you do

```typescript
store.assign(props)
```

to update the store with new data from your parent component? Primitive data is simple. Their observables are updated with the new data...an observable?

What I'm doing is weird so I will just refactor this away to be honest. Happy to close this, I just thought I'd mention it.

**Comment by jmeistrich** [comment]
Thanks @briandipalma! It's been a known issue for a while, but we have a solution to it in a project we're working on. The project is fairly big so it might be a couple of weeks before it gets into normal releases.
