### ISSUE TITLE
Wrapping observable.set within startTransition breaks atomic updates

### ISSUE THREAD

**Issue by MrFlashAccount** [LegendApp/legend-state#22]
Hi! `legend-state` is fantastic, and I love it! 

I've been playing with your demo on codesandbox and found that wrapping `count.set(...)` in `startTransition`(means enabling concurrent mode) breaks atomic updates:  [link](https://codesandbox.io/s/legend-state-tree-forked-erbm91?file=/src/App.tsx). 

https://user-images.githubusercontent.com/61194245/194503391-f4c2ab29-cb09-4d56-a491-fc7a36af9fb3.mp4

I attached a video showing that components rerender four times each time the count updates.

Is it intended? Any plans for supporting concurrent rendering?

Thanks!

**Comment by jmeistrich** [comment]
Oh very interesting! Thank you for a good repro. We absolutely should support concurrent rendering so I will take a look at fixing it this weekend.

**Comment by MrFlashAccount** [comment]
@jmeistrich
> startTransition runs a useState under the hood, calling setPending(true) and then setPending(false)

This 👆 is 🤯. New information for me. Thank you for the investigation!
