### ISSUE TITLE
how to show object list type correctly ? 

### ISSUE THREAD

**Issue by lawplatform** [LegendApp/legend-state#220]
I aim to store messages and display them using the map function, 
but I encountered an issue. 
The error message indicates: 'Property 'msg' does not exist on type 'ObservablePrimitiveBaseFns<msgtype|undefined>.'

so I delete <for> and try to show data using map 
and error messaeg disappeared.

```
type msgtype = {
	id: number
	msg: string
	name: string
}
export default function Home() {
	//const state$ = observable({ messages: [] });
	const state$ =
		useObservable({ msg: [] as msgtype[], })
	const add = () => {
		state$.msg.push({
			id: 0,
			msg: "hi",
			name: "yoon"
		})
		console.log(state$.get());
	}
	return (
		<div>
		        <div className="h-52">
				{state$.msg.map((m) => (
					<p>{m.msg.get()}</p>
				))}
			</div>
			<Input type="text" />
			<Button onClick={add} > click</Button>
		</div >
	)
}
```

Despite successfully adding a new 'msg' object using 'push' and confirming its addition in the log, there is an obstacle in displaying the list in the return statement through the map function.

I attempted to resolve the issue by changing 'useObservable' to 'observable(),' but this modification did not resolve the problem. How can I address this issue effectively?"

**Comment by jmeistrich** [comment]
You need to make the component reactive to changes first. See the first section on the introduction to React page for how to do that: https://legendapp.com/open-source/state/react/react-introduction/

The easiest option to get started is `enableReactTracking()`:

```js
import { enableReactTracking } from "@legendapp/state/config/enableReactTracking";

enableReactTracking({
    auto: true,
});
```
