### ISSUE TITLE
Problem with createObservableHook Usage, functions no exported

### ISSUE THREAD

**Issue by realzam** [LegendApp/legend-state#224]
### Description:

I'm encountering an issue while trying to utilize the createObservableHook. When attempting to execute a function from the original hook, it fails to work.
### Details:

- TypeScript successfully detects all properties without any issues.
- However, during execution, an error is thrown, indicating that the functions do not exist.
- Upon logging the value in the console, it only displays variables rather than both variables and functions.
### Uncertainty:

I'm uncertain about where the error might be originating from. I would greatly appreciate guidance on where I might be going wrong.

```typescript
export const useCounter = () => {
  const [counter, setCounter] = useState(0);
  const increment = () => {
    setCounter((c) => c + 1);
  };

  const decrement = () => {
    setCounter((c) => c - 1);
  };

  const reset = () => {
    setCounter(0);
  };
  return {
    counter,
    increment,
    decrement,
    reset,
  };
};
```

```typescript
import { createObservableHook } from '@legendapp/state/react-hooks/createObservableHook';

const useMyHookObservable = createObservableHook(useCounter);
const value = useMyHookObservable();
const {counter,increment,decrement,reset}=value.get()
...
<button onClick={increment}>+1<button>

```

**Comment by jmeistrich** [comment]
`createObservableHook ` is an experimental hack to try to convert existing hooks to make them work with observables. But I think it doesn't actually work in most cases so we should probably remove it.

If you're just trying to create observables you probably want to use [useObservable](https://legendapp.com/open-source/state/react/react-api/#useobservable) instead of `useState`.

**Comment by realzam** [comment]
Ohh i see, i'm trying void rerender from external hooks. Thaks
