### ISSUE TITLE
Docs: Add note about non-keyed benchmark

### ISSUE THREAD

**Issue by aaron-manning** [LegendApp/legend-state#24]
Hi,

I was intrigued by the performance claims of this library and realised that you aren't comparing apples to apples with the 'optimized' [krausest](https://github.com/krausest/js-framework-benchmark) benchmark, seen here:

![image](https://user-images.githubusercontent.com/32957675/194518110-b1d8c898-f11d-4afc-ab60-0f6b1fafe867.png)

It appears to me that you are comparing a non-keyed implementation of the benchmark (the optimized bench re-uses nodes) to keyed implementations. 

I suggest that you add a note to the following page that the optimised benchmark is not keyed, so at to not confuse.
https://legendapp.com/open-source/state/fast/

Thanks

**Comment by jmeistrich** [comment]
Done in the latest docs.
