### ISSUE TITLE
Observe property in computed observable is not working properly

### ISSUE THREAD

**Issue by phuongphamx96** [LegendApp/legend-state#246]
Hi, I had some issues when I'm working with Legend State. Please advise.
Suppose the code is:
```
"use client";

import { computed, observable, observe } from "@legendapp/state";
import { Memo } from "@legendapp/state/react";

const state = observable({
  a: {
    prop1: 1,
    prop2: 2,
  },
  b: {
    prop1: 3,
    prop2: 4,
  },
});

const editingId = observable<"a" | "b">("a");
const editingItem = computed(() => state[editingId.get()]);

export default function Home() {
  return (
    <div>
      Editing Id: <Memo>{editingId}</Memo>
      <br />
      Editing Item: <Memo>{() => JSON.stringify(editingItem.get())}</Memo>
      <br />
      <button onClick={() => editingId.set("b")}>change editing id</button>
      <button onClick={() => editingItem.prop2.set((prev) => prev * 10)}>
        change editing item prop2
      </button>
    </div>
  );
}

observe(() => {
  console.log("prop1", editingItem.prop1.get());
});

observe(() => {
  console.log("prop2", editingItem.prop2.get());
});
```

1. When I use v2.1.8
- When I click on "change editing item prop2" button, the log is
```
prop2 20
```
-> It's correct, prop1 is not printed, no issues here
- But, when I click on "change editing id" button, the computed `editingItem` is not changed
[v2.1.8.webm](https://github.com/LegendApp/legend-state/assets/37136659/a49c8371-b227-441b-bb8b-45898896b0b1)
2. When I use v2.2.0-next.41
- When I click on "change editing id", now the computed `editingItem` is changed correctly.
- When I click on "change editing item prop2", both `prop1` and `prop2` are printed. I expect that `prop2` is printed only.
[v2.2.0-next.41.webm](https://github.com/LegendApp/legend-state/assets/37136659/c40e95a8-fc74-425d-8a5d-9d8f97f0979d)

Please advise me how to address this issue at this time.
Thank you.

**Comment by jmeistrich** [comment]
Ah good catch, thank you! The computed in 2.1.8 is known to be bugged in that way (which is why we're making the changes in @next). So I've made a failing test for the bug you found in @next and am working on it now.

**Comment by jmeistrich** [comment]
Fixed in next.42. Please let me know if you see any more issues! 

Note that the code that fixed it is a bit messy and verbose, because getting deeply nested observable links to work correctly and be reactive as expected is very complex 😅. I'm aiming for 100% correctness with extensive tests for every case I can think of, and then I'll rethink the architecture to improve performance and bundle size, so finding incorrect behavior is very appreciated ❤️
