### ISSUE TITLE
useMountOnce run twice in dev?

### ISSUE THREAD

**Issue by yueliangwen** [LegendApp/legend-state#252]
The useMountOnce runs twice without the dispose function in dev, it's just an alias for useEffectOnce, but useUnmountOnce runs only once in dev. 
I think the useMountOnce should run only once in dev. It's a design or a bug?

**Comment by jmeistrich** [comment]
It looks like those workarounds got slightly broken over time and the tests weren't good enough. I've got it fixed for the upcoming version 3.0 version.

**Comment by jmeistrich** [comment]
This should be fixed in 3.0 alpha so I’m going to close this issue, but if it still isn’t working right for you please let me know!

**Comment by ignissak** [comment]
Happens on 3.0.0-beta.19, using useMountOnce and happens after navigating back to the component after mounting it the first time.
