### ISSUE TITLE
Issue with updating particular array, all arrays are updated with same data. Am I doing this wrong?

### ISSUE THREAD

**Issue by nikocraft** [LegendApp/legend-state#253]
Just dicovered this lib and migrating to it from Zustand since I needed the fine-grained reactivity that allows me to have more control of what gets re-rendered. I love the library so far. The only issue I may have run into has to do with arrays.
here is some code of my store

```
import { batch, observable } from '@legendapp/state'

interface SoundChannel {
  sound: Audio.Sound | null
  file: SoundFile | null
  isPlaying: boolean
  intervalId: number | null
  warmUpTimeoutId: number | null
}

interface AudioPlayerState {
  channels: SoundChannel[]
  isPlaying: boolean
  currentSoundscape: { title: string; image: ImageSourcePropType } | null
}

const initialState: AudioPlayerState = {
  channels: Array(5).fill({
    sound: null,
    file: null,
    isPlaying: false,
    intervalId: null,
    warmUpTimeoutId: null,
  }),
  isPlaying: false,
  currentSoundscape: null,
}
const audioStore$ = observable(initialState)
```

As you see I have an array of channels that I have prefilled. Later I have need to update particular item in the array and particular property inside the item.

Inside my store, in the same file I have this function:

```
export const loadSoundFile = async (channelIndex: number, file: SoundFile) => {
  const channels = audioStore$.channels.get()
  await channels[channelIndex].sound?.unloadAsync()
  const { sound } = await Audio.Sound.createAsync(soundAssets[file.name])
  const status = await sound.getStatusAsync()
  ...
  ...
  *** this code here is where the issue is, it updates the entire array instead of just item at [0] ***
  batch(() => {
    console.log('batch started', channelIndex)
    audioStore$.channels[0].sound.set(sound)
    audioStore$.channels[0].file.set(file)
  })
  
  console.log('after batch')
  channelsTmp.map((channel, index) => {
    console.log('channel:', channel.file.name, 'index:', index)
  })
```

Since I started experiencing this bug where the above code would update all 5 channels instead of just channel at index 0, I even hardcoded it to 0 just to make sure only item at [0] is getting updated. The above code batch code is only called once and it only runs once, yet after it has finished all 5 item in the array are filled with exact same file and sound data and before the update all 5 items where at initial values created by fill. Both my application and console logs confirm that.

Am I updating the array item wrong? I assumed since there are no typescript complaints and errors that this will work:
 
```
 audioStore$.channels[0].sound.set(sound)
 audioStore$.channels[0].file.set(file)
```

Is this not the correct way to update an array item property? Do I have to do it like this instead which is more verbose and involves creating new array 

```
  audioStore$.channels.set((prevChannels) => {
    const updatedChannels = [...prevChannels];
    updatedChannels[channelIndex] = {
      ...updatedChannels[channelIndex],
      sound: sound,
      file,
    };
    return updatedChannels;
  });
```

If that is the way to do it, how does Legend-State know what array item was updated so that it doesn't re-render all channel components on screen instead of particular one that got updated?

I'd appreciate if someone would let me know if this is either a bug and it should work the way I attempted it or let me know if second approach is correct and Legend will figure out what item got updated, and not flag every channel component for re-render.

**Comment by nikocraft** [comment]
It seems library is designed to supports this approach:
 ```
audioStore$.channels[0].sound.set(sound)
audioStore$.channels[0].file.set(file)
```
But it fails to do so when array is setup like this:
   
```
const initialState: AudioPlayerState = {
  channels: Array.from({ length: 5 }, (_, index) => ({
    _id: index + 1,
    sound: null,
    file: null,
    isPlaying: false,
    intervalId: null,
    warmUpTimeoutId: null,
  })),
  isPlaying: false,
  currentSoundscape: null,
  modalState: PlayerModalStates.CLOSED,
}

const audioStore$ = observable(initialState)
```
which is a pre-filled array. 


Could this old issue still be in some form active? https://github.com/LegendApp/legend-state/issues/50


I got the batch to work BUT I had to do a hack with the library first, see the screenshot. I would love to hear from one of the developers what they think is causing this issue I've found.


If I before batch do this, just create a new array and set it, and than run batch, only one channel at correct index is updated and there are no issues.
![image](https://github.com/LegendApp/legend-state/assets/443080/ce170d51-a55d-4d81-9563-54900b785eec)

Could someone in dev team take a look while batch fails when prefilled array is used?

**Comment by jmeistrich** [comment]
I think the problem is the `Array(5).fill({...})` - that fills the array with 5 references to the same item. The hack fixes it because it clones each array element so they're different items.

But I would have expected changing it to `Array.from` to fix it, so I'm not sure what the problem is without seeing the rest of your code. Can you share a minimal reproducible code sample that I can test with?

**Comment by nikocraft** [comment]
@jmeistrich you are right Array.from fixed it! I a reset channels function running which also used Array(5).fill, now that I have switched it to Array.from everything is good! :)
