### ISSUE TITLE
Persistence with React Native MMKV

### ISSUE THREAD

**Issue by dustinvforsyth** [LegendApp/legend-state#268]
It took me a minute to figure out the persistence with the built in MMKV plugin you built. My issue was I didn't know what to put in the persistence object. I found that this worked even without configuringPersistence code mentioned in the documentation:

```
persistObservable(
  { initialValue: 'CoolString' },
  { local: 'StoreKey', pluginLocal: ObservablePersistMMKV },
)
```

This Didn't work for me: 

```
configureObservablePersistence({
   pluginLocal: ObservablePersistMMKV,
});

persistObservable(
  { initialValue: 'CoolString' },
  { local: 'StoreKey' },
)
```

So I am curious if the documentation is out of date and I don't actually need to do configureObservablePersistence or if there is something wrong with the way I am doing it? 

I will add it did work with configure but I still had to have the `pluginLocal: ObservablePersistMMKV` value in the persistenceOptions for it to work that seemed like the missing link for me.

Thanks so much for a great library have loved how simple and fast it is! Also I am willing to pull request an update to the docs if it turns out that they are out of date or need more info.

**Comment by jmeistrich** [comment]
It seems like the documentation could be clearer. You can set options for each individual observable like you've done, and that's fine. Or you can set defaults in `configureObservablePersistence` which you can then override in each observable. 

But what you said didn't work should work... One thing to note which isn't called out well in the docs is that it caches any changes made after calling `persistObservable`, so the initial value would not be saved. Is that what wasn't working or did you encounter other issues? Can you share a full example I can use to test it?

**Comment by dustinvforsyth** [comment]
Ok that makes sense I figured it was more of a global config thing. Here is a snack that is setup how I was doing it. I am not sure if this would work the same in the expo go app as it was on mine as I am ejected completely. 
https://snack.expo.dev/@dustinvforsyth/legendstate-mmkv-issue-repro

It looks like it's reproducible with this snack but like I said it might just be because of expo go. Either way this is the way I have it setup and it's not working. 

Let me know if I am just doing something wrong here. Like I said I have it working just fine without using the global config just trying to make sense of it all.

**Comment by jmeistrich** [comment]
I think the problem is 
```
const $state = persistObservable({ isSet: false }, { localStorage: 'stateValue'});
``` 

If you change `localStorage` to `local` it should work:
```
const $state = persistObservable({ isSet: false }, { local: 'stateValue'});
```

**Comment by dustinvforsyth** [comment]
Oops sorry that was a bad reproduction. I am actually using `local` instead of `localStorage`. I updated the snack to reflect that.

When I `const $state = persistObservable({ isSet: false }, { local: 'stateValue'});` 
With the configGlobal just like I have in the snack I get the following error in the console:
`Error: Local persistence is not configured`


As long as I put the following it works as expected: 
`const $state = persistObservable({ isSet: false }, { local: 'stateValue', pluginLocal: ObservablePersistMMKV });`

**Comment by jmeistrich** [comment]
Oh gotcha! In that case I think it's just an order of execution problem - AssetExample is imported before the call to `configureObservablePersistence` so `persistObservable` is called before `configureObservablePersistence`. 

One way to solve that could be to create something like a `config.ts` which calls `configureObservablePersistence` and make sure it's imported first in `App.js` so that it runs before everything else.

**Comment by dustinvforsyth** [comment]
That makes sense. 

I tried moving the `configureObservablePersistence` to be imported and configured before anything else in the app very top of `App.js`  and I still get the error `Error: Local persistence is not configured`. 

Any other thoughts?

**Comment by jmeistrich** [comment]
Can you share that project? I tried adjusting that snack to just run `configureObservablePersistence` before `persistObservable` and it throws an error that mmkv doesn't work in Expo Go, which at least means it's configured 😅. So I'm pretty sure it must just be an import ordering thing. I think some environments might run imports before they run the code in the files, so the order may be unintuitive. Try putting some console logs before the function calls to see what order they're going in?

https://snack.expo.dev/@legendapp/legendstate-mmkv-issue-repro

**Comment by dustinvforsyth** [comment]
Hey thanks so much for walking me thought all this @jmeistrich. 

You were right it's totally an import order issue. I copied what you did in your snack and just put the global config right before I setup a persistent state and it worked as expected.

Guess I need to research a little more about how import ordering works. I am guessing it probably would have worked if I had thrown it down into a `config.ts` to be imported first thing.

Thanks again for all the help and this awesome library!
