### ISSUE TITLE
Async Storage Persistence doesn't seem to work

### ISSUE THREAD

**Issue by Inalegwu** [LegendApp/legend-state#269]
I am currently working on a React Native project and have recently migrated from Zustand to legend for my state mangagement and everything works fine till I try using the persist plugin.

Observables aren't persisted to AsyncStorage despite following the guide in the docs closely and even after ensuring the storage was cleared and clearing the application cache as well.

If anyone else has had a similar issue , I will be very grateful for their help.

my code looks like this

```ts
// config
configureObservablePersistence({
  pluginLocal: ObservablePersistAsyncStorage,
  localOptions: {
    asyncStorage: {
      AsyncStorage,
    },
  },
});

// actual store
persistObservable(globalState, {
  local: "app_state",
});
```

**Comment by jmeistrich** [comment]
`persistObservable` saves any changes made after the call to `persistObservable`. Are modifications after that not being saved? This trips up a lot of people - we're working on updating the docs to call that out.

If that's not it, could you share a bit more of your code? Are you seeing any error messages?

**Comment by Inalegwu** [comment]
Modifications to the store being passed to ```persistObservable``` aren't being saved.
Alternatively , I suspect it might be due to the use of snippets like these that may be causing the issue , either that or because the components aren't wrapped by the Observer HOC
```ts
export function logout() {
  globalState.auth.set({
    loggedIn: false,
    token: null,
  });
}

export function login(user: User, token: string) {
  globalState.auth.set({
    loggedIn: true,
    token,
  });
  globalState.user.set(user);
}
```

**Comment by Inalegwu** [comment]
Here is a full snippet of my code definining the observable as well as registering persist and configuring it

```ts
// persist
configureObservablePersistence({
  pluginLocal: ObservablePersistAsyncStorage,
  localOptions: {
    asyncStorage: {
      AsyncStorage: {
        ...AsyncStorage,
      },
    },
  },
});
// state definition
import { observable } from "@legendapp/state";
import { persistObservable } from "@legendapp/state/persist";
import { ProfileImage } from "@src/lib/types";

type User = {
  email: string;
  password: string;
  timelast?: string;
  lastSeen?: string;
  userId?: string;
};

type GlobalState = {
  auth: {
    loggedIn: boolean;
    token: string | null;
  };
  user: User | null;
  profile: {
    image: ProfileImage;
    url: string | null;
  };
};

const globalState = observable<GlobalState>({
  auth: {
    loggedIn: false,
    token: null,
  },
  user: null,
  profile: {
    image: "default",
    url: null,
  },
});

export function logout() {
  globalState.auth.set({
    loggedIn: false,
    token: null,
  });
}

export function login(user: User, token: string) {
  globalState.auth.set({
    loggedIn: true,
    token,
  });
  globalState.user.set(user);
}

// call persist observable
persistObservable(globalState, {
  local: "app_state",
});

export default globalState;

```
Is there anything I could have missed , I did follow the documentation to get to this point

**Comment by jmeistrich** [comment]
It may be this bit:
```js
localOptions: {
    asyncStorage: {
      AsyncStorage: {
        ...AsyncStorage,
      },
    },
  },
```
I think that should be just 
```js
localOptions: {
    asyncStorage: {
      AsyncStorage
    },
  },
```

And are you actually running `configureObservablePersistence` above the imports? Or is it in a different file? Imports can sometimes go in an unexpected order, so the `configureObservablePersistence` might actually be running after the state definition. Try putting that at the top of the same file (below the imports)?

**Comment by Inalegwu** [comment]
I'm running ```configureObservablePersistence``` from my main file(App.tsx) as described in the docs.

**Comment by Inalegwu** [comment]
Thank you very much for your help , I moved ```configureObservablePersistence``` to the top of the state definition file and it works , thanks very much for your help

**Comment by jmeistrich** [comment]
Great, glad it's working!

**Comment by Inalegwu** [comment]
This issue is quite the sporadic one.
with no changes to configuration, persistence randomly fails.It seems to have a period in time which it remains persisted before being purged.

**Comment by Inalegwu** [comment]
After digging into the issue a bit more, it appears that legend state is writing an unresolved promise to async storage as opposed to the final result of the promise.I assume this is issue is related to the method being used to persist data
