### ISSUE TITLE
TypeError: Cannot assign to read-only property '', js engine: hermes after app reloads

### ISSUE THREAD

**Issue by lukertaylor** [LegendApp/legend-state#272]
I am creating a shopping list app. My data model includes an array of Lists. Each List contains an array of ListItems.

When I add ListItems to an existing List, I can then delete the items. However, as soon as I re-load the app, I get the following message as soon as I try to delete a ListItem:

`TypeError: Cannot assign to read-only property 'listItems', js engine: hermes`

I am persisting my data within AsyncStorage.

I've stripped my code as much as possible to provide a simple example:

```
import { Stack, useLocalSearchParams } from 'expo-router';
import { StatusBar } from 'expo-status-bar';
import { FlatList, StyleSheet } from 'react-native';
import { store$ } from '../../_layout';
import { observer } from '@legendapp/state/react';
import ListItem from '../../models/ListItem';
import ListItemCard from '../../components/ListItemCard';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import FloatingActionButton from '../../components/FloatingActionButton';
import Item from '../../models/Item';

type ParamsType = {
  listId: string;
};

const EditListScreen = observer(() => {
  const { listId } = useLocalSearchParams<ParamsType>();
  const listItems = store$.lists
    .find((list) => list.get().id === listId)!
    .listItems.get();

  function deleteListItem(listItemId: string) {
    const updatedListItems = listItems.filter(
      (listItem) => listItem.id != listItemId
    );
    store$.lists
      .find((list) => list.get().id === listId)!
      .listItems.set(updatedListItems);
  }

  function addListItem() {
    const item1 = new Item({ title: 'Greek yogurt' });
    const newListItem1 = new ListItem({ item: item1, quantity: 2 });
    const item2 = new Item({ title: 'Baked beans' });
    const newListItem2 = new ListItem({ item: item2 });
    store$.lists
      .find((list) => list.get().id === listId)!
      .listItems.set((prevListItems) => [
        ...prevListItems,
        newListItem1,
        newListItem2
      ]);
  }

  return (
    <>
      <Stack.Screen options={{ title: 'Edit list' }} />
      <GestureHandlerRootView style={styles.container}>
        <FlatList
          data={listItems}
          renderItem={({ item }) => (
            <ListItemCard
              listItem={item}
              deleteListItem={() => deleteListItem(item.id)}
            />
          )}
          keyExtractor={(item) => item.id}
        />
      </GestureHandlerRootView>
      <FloatingActionButton onPressAction={addListItem} />
      <StatusBar style="auto" />
    </>
  );
});

export default EditListScreen;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center'
  }
});
```

Any thoughts?

**Comment by jmeistrich** [comment]
I can't really tell from that what the problem could be. I'm guessing it might be that `Item` and `ListItem` are classes? It wouldn't know how to restore them from storage as classes so they'd be normal objects instead. So that may be causing the issue? Can you share what those look like? 

Do you have a stack trace for where that `TypeError` is happening? And to clarify the problem - the error is happening if you create an item, reload, and then delete that item?

Probably unrelated but you can also simplify the code a bit. Legend-State doesn't have the same immutability requirements that regular React has, so it's more efficient and easier to operate directly on the arrays than to clone them.

Keep a reference to the `list$` observable so you don't need to `find` it on every operation:
```ts
const { listId } = useLocalSearchParams<ParamsType>();
const list$ = store$.lists.find((list) => list.get().id === listId)!;
const listItems = list$.listItems.get();
...
```

And you don't need to clone the array, just splice out the element you want to delete:

```ts
function deleteListItem(listItemId: string) {
  const idx = listItems.findIndex(
    (listItem) => listItem.id === listItemId
  );
  list$.splice(idx, 1);
}
```

And in add you can just push instead of cloning in set:
```ts
function addListItem() {
    const item1 = new Item({ title: 'Greek yogurt' });
    const newListItem1 = new ListItem({ item: item1, quantity: 2 });
    const item2 = new Item({ title: 'Baked beans' });
    const newListItem2 = new ListItem({ item: item2 });

   list$.push(newListItem1, newListItem2);
}
```

**Comment by lukertaylor** [comment]
Hi Jay (@jmeistrich), thanks a lot for your reply. I re-created a very basic version of my app with the same models and just the functions to add a list, add two list items and delete them. I cannot recreate the error that is occurring in my main app. So I'm sure it's a problem with my app and nothing to do with Legend State.

My basic app is available at: https://github.com/lukertaylor/legend-test

Thank you also for the tips on cleaner code - much better. I'm new to Legend State, so still getting used to it.

I really like the easy to read code one gets with Legend State, and I also chose it because I want to eventually move to it being an offline first app.

Thank you for contributing it as Open Source - it's a great solution.
