### ISSUE TITLE
`persistObservable`: `targetChild.set()` is not a function error

### ISSUE THREAD

**Issue by niravcodes** [LegendApp/legend-state#275]
Hi :)

I have the following state:

```js
import { configureObservablePersistence, persistObservable } from "@legendapp/state/persist";
import { ObservablePersistLocalStorage } from "@legendapp/state/persist-plugins/local-storage";
import { observable, computed } from "@legendapp/state";

configureObservablePersistence({ pluginLocal: ObservablePersistLocalStorage });

const draftBom$ = observable({
  items: [],
  addItem(item) {
    const newItems = Array.from(new Set(draftBom$.items.get()).add(item));
    draftBom$.items.set(newItems);
  },
  deleteItem(item) {
    const newItems = draftBom$.items.get().filter((i) => i !== item);
    draftBom$.items.set(newItems);
  },
});

const bomDraftLength$ = computed(() => draftBom$.items.get()?.length ?? 0);

persistObservable(draftBom$, { local: "draftBom" });
```

It works flawlessly when run locally, whether in dev or prod mode. I can not find any fault with this simple code.

But only when I deploy it to a server I get this cryptic minified error:

<img width="516" alt="Screenshot 2024-04-24 at 01 19 14" src="https://github.com/LegendApp/legend-state/assets/23399099/2cc1ca1d-8a8e-4d29-83e4-ac70868a5e1e">

Upon tracing it in the Legend state source code, looks like this function `targetChild.set()` might not always exist.

https://github.com/LegendApp/legend-state/blob/2d8e015c6b1d725bd46f488652f682399da1a028/src/helpers.ts#L166

It's strange that it only happens on the server, and I can't replicate it anywhere else. 

And when I remove the `persistObservable` line, the problem goes away. I am trying to find if the issue is something on the my end. But I'm reporting it here anyway, because there seems to be an edge case where `targetChild.set()` is not a function.

**Comment by jmeistrich** [comment]
I think it is having a problem persisting an object with functions in it. I just wrote a test for perssiting with funcitons and found some issues there. I’ll try to get a fix for that out asap. 

But if you change to just persist the items array it should all work fine:
```js
persistObservable(draftBom$.items, { local: "draftBom" });
```

**Comment by niravcodes** [comment]
Thanks a lot! It _was_ the functions in the state. 

Since it's already fixed for v3, I'll close this issue.
