### ISSUE TITLE
Type of array element typed T is any

### ISSUE THREAD

**Issue by lishine** [LegendApp/legend-state#278]
Specifically when the element type is `T`, the type of `ar$[index].get()` is `any` , while is the type of  `ar$.get()[index]` is correct.

Reproduction - hover over `checkTypeOfThisVar`:
https://stackblitz.com/edit/vitejs-vite-u8wu5u?file=src%2FApp.tsx

I noticed that problem when setting `$ar[index].set(the param is any)`

**Comment by jmeistrich** [comment]
I think this should be fixed in the @next version. Or is it still a problem?
