### ISSUE TITLE
Type of useComputed(()=>observable)

### ISSUE THREAD

**Issue by lishine** [LegendApp/legend-state#281]
Type not unwrapped

```ts
    const a$ = useObservable(1)
    const $c = useComputed(() => {
        return a$
    }, [a$])
    let c = $c.get()
```
Type of `c` should be `number`, but it is: `ObservablePrimitiveBaseFns<number>`

Type of `$c` also should not be `ObservableComputed` because it will not allow `set`.

**Comment by lishine** [comment]
I understand that in v3 you intend to unite some types?
I am currently aligning our code with two kind of types:
`Observable - read/write`
`ObservableComputed - readonly`
I don't see need in my code for any other types for observables like ObservableObject etc.

**Comment by jmeistrich** [comment]
This should be fixed in v3 @alpha. Computed is no longer a separate concept and types were much improved, so I think this should be correct now? But please let me know if you still see any issues and we can re-open this issue.
