### ISSUE TITLE
Clear store when the user logs out

### ISSUE THREAD

**Issue by Mihai-github** [LegendApp/legend-state#285]
How can we clear the store when for example a user deletes his account or signs out? setting the store with the initial value provided seems like is not working as expected

**Comment by jmeistrich** [comment]
The best way is to use the `clearPersist` function on the synced state. In the latest version 3, `syncObservable` now returns the sync state, or you can use `syncState` to get the sync state of any observable. See https://legendapp.com/open-source/state/v3/sync/persist-sync/#syncstate

You can use it like
```js
const state = syncObservable(store$, {…})
state.clearPersist()
```

In version 2 it was returned as a `state` child of `persistObservable` , so in 2.x it would have looked like:
```js
const { state } = persistObservable(store$, {…})
state.clearLocal()
```

Please let me know if this doesn't work as expected!
