### ISSUE TITLE
Calling Observable.get() twice causes component to not render after state is changed using .set()

### ISSUE THREAD

**Issue by Jakemangan** [LegendApp/legend-state#287]
I imagine this is probably just not me understanding the library as I'm new to it, however I can't see anything in the docs that would specify why this is happening. 

In the below code I am creating an observable, checkIndex. CheckIndex is just an array of numbers which is then used by the component to decide when to display a \<Text> containing a string "Check". If the index of the list item is present in checkIndex then display the \<Text>, pretty simple. 

When any ListItem is pressed, it should either add or remove its index to checkIndex, depending on whether it's present in the array already. This works fine for adding, there's no issues. 

But for removing, it only works assuming I don't use checkIndex.get() a second time. If I do, then "render" is never logged by the component and the component is never updated. If I remove the second checkIndex.get() and instead use the refderence to checkIndexArray to create a new array using the spread operator, then everything works as expected. 

However newCheckIndexArray and the return of checkIndex.get() are identical, as newCheckIndexArray is created using checkIndex.get() higher up in the code. So the operation should be exactly the same in terms of the objects being operated on.

I can only assume .get() is quietly doing something here that I don't understand which is causing an issue when .get() is being called twice. But I don't know what. Calling it a third time doesn't change anything, it still doesn't work. But if I only call checkIndex.get() once everything else works okay.

Also, does .set() cause a render when the observable is updated?

```
export default function SelectExerciseModal() {
  const checkIndex = useObservable<number[]>([]);

  const handleOnPress = (exercise: Exercise, listItemIndex: number) => {
    let checkIndexArray = checkIndex.get();
    if (checkIndex.get().includes(listItemIndex)) {
      let index = checkIndexArray.indexOf(listItemIndex);
      let newCheckIndexArray = [...checkIndexArray]; //Causes render to be logged by the component below
      // let newCheckIndexArray = checkIndex.get(); //Render isn't logged by the component 
      newCheckIndexArray.splice(index, 1);
      checkIndex.set(newCheckIndexArray);
    } else {
      checkIndex.set([...checkIndex.get(), listItemIndex]);
    }
  };

  return (
    <For each={exerciseState$}>
      {(item, index) => (
        <YGroup.Item>
          <ListItem onPress={() => handleOnPress(item.get(), parseInt(index))}>
            <XStack flex={1} justifyContent="space-between">
              <Text>{item.get().name}</Text>
              <Show
                if={() => {
                  console.log("render");
                  return checkIndex.get().includes(parseInt(index));
                }}
              >
                <Text>Check</Text>
              </Show>
            </XStack>
          </ListItem>
        </YGroup.Item>
      )}
    </For>
  );
}
```

**Comment by jmeistrich** [comment]
By the way, this is a very common issue since React developers are used to state being immutable. So I wrote up some notes about that in the docs for the upcoming version 3. https://preview.legend.pages.dev/open-source/state/v3/usage/observable/#observables-are-mutable

**Comment by Jakemangan** [comment]
Hi @jmeistrich, just had a chance to look over your reply now. I've altered my code around as per your suggestions and it's working perfectly now. I think it was the immutability differences that were the gap in my knowledge. 

Thank you for your help, I'll make sure to read over the v3 docs as well. I'll close this off.

When is v3 coming out? I'm a big fan of your guys work, this is exactly the state management library I was envisioning when I started working with React.

**Comment by Jakemangan** [comment]
Also, would you mind just telling me what the difference is in doing 

`let index = checkIndex.get().indexOf(listItemIndex);`

vs 

`let index = checkIndex.indexOf(listItemIndex);`

**Comment by jmeistrich** [comment]
v3 alpha is out now :)

There is no difference between those two. Many of the observable array methods work a bit differently by passing the observable to the callback, but `indexOf` is unchanged: https://legendapp.com/open-source/state/v3/usage/observable/#arrays
