### ISSUE TITLE
For component infers types wrong in Typescript

### ISSUE THREAD

**Issue by jansedlon** [LegendApp/legend-state#288]
Hey 👋 Just found this library and decided to give it a try.

I just wanted to use it for a simple(ish) use case in my app so i followed the "List of messages example" in react section.

I created observable like this 

```ts
const {modules} = useObservable({
  modules: loaderData.course.modules,
});
```

The type for `modules` looks like this

```ts
JsonifyObject<{
    id: string;
    status: "PUBLISHED" | "DRAFT";
    title: string;
    position: number;
    sections: {
        id: string;
        status: "PUBLISHED" | "DRAFT";
        title: string;
        position: number;
    }[];
}>[]
```

Then i render it like 

```tsx
 <For each={modules} optimized>
  {(courseModule) => {
    const index = getObservableIndex(courseModule);
    console.log(index, courseModule.id.get());

    return <div></div>;
  }}
</For>
```

However i think the type for `courseModule` is not inferred correctly because it says that property `id` does not exist. I wanted to call `courseModule.id.get()`

```
Property 'id' does not exist on type 'ObservablePrimitiveBaseFns<JsonifyObject<{ id: string; status: "PUBLISHED" | "DRAFT"; title: string; position: number; sections: { id: string; status: "PUBLISHED" | "DRAFT"; title: string; position: number; }[]; }> | undefined>'.
```

Am i missing something?

**Comment by jansedlon** [comment]
May be related #266 ?

**Comment by jmeistrich** [comment]
Hmm, I’m not sure what it would be, but the types are much improved in the next version, so if it’s fix there then I think we’re all good - it’s coming to v3 alpha soon.
