### ISSUE TITLE
observableFetch missing in next version

### ISSUE THREAD

**Issue by jansedlon** [LegendApp/legend-state#292]
Hello :) I'm using the next tag version and noticed that the observableFetch utility is missing. Is there an alternative? Tried to find it via commit history but seems like it's completely removed

**Comment by jmeistrich** [comment]
Oh yes, I actually just released 3.0 alpha today but it got late so I haven’t announced it just yet. The new version has a new sync system with a much better way of doing fetch. See
- https://legendapp.com/open-source/state/v3/sync/fetch/
- https://legendapp.com/open-source/state/v3/sync/persist-sync/

**Comment by jansedlon** [comment]
Ah you're right, i was not sure if that's the right thing, thanks! :)
