### ISSUE TITLE
Module '"@legendapp/state/history"' has no exported member 'undoRedo'. on `3.0.0`

### ISSUE THREAD

**Issue by flexbox** [LegendApp/legend-state#293]
as a user,
I can use `undoRedo`,
so that I can build a travel history feature

problem
I can't import `undoRedo`

reproductible repository
https://codesandbox.io/p/sandbox/silent-microservice-r3jyxt?file=%2Fsrc%2FApp.tsx%3A17%2C9

**Comment by jmeistrich** [comment]
Oh you caught that quickly! Sorry about that, I realized it last night and moved it to /helpers but I hadn’t pushed it yet. I’ll release an update shortly which will have it under /helpers/undoRedo. I’ll reply again when it’s released.

**Comment by flexbox** [comment]
No worries 😉
It’s literally written `alpha`
i just wanted to try out this new feature because that’s literally what I’m working on these days.

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=ZGxldWxpZXR0ZUBnbWFpbC5jb20=>

**Comment by jmeistrich** [comment]
Fixed in alpha.1 😀. It’s now at `import { undoRedo } from '@legendapp/state/helpers/undoRedo’`
