### ISSUE TITLE
Suspense gives error - v3

### ISSUE THREAD

**Issue by lishine** [LegendApp/legend-state#295]
https://stackblitz.com/edit/vitejs-vite-laqs1y?file=src%2FApp.tsx

**Comment by lishine** [comment]
update: the dependency in the link was v2
now it is v3 and i updated the above post

**Comment by lishine** [comment]
Here is a test
```ts
    test('suspense', async () => {
        const obs$ = observable(new Promise<string>((resolve) => setTimeout(() => resolve('hi'), 0)));
        const isDone$ = observable(undefined as string | undefined);
        const Test = observer(function Test() {
            const value = useSelector(obs$, { suspense: true });
            isDone$.set(value);

            return createElement('div');
        });
        function App() {
            return createElement(Suspense, { fallback: createElement('div') }, createElement(Test));
        }
        render(createElement(App));
        expect(await when(isDone$)).toEqual('hi');
    });
```

For the best test implementation jsconfig should be updated with jsdom env.
I saw there happy-dom, tried to run bun, but it does not run tests out of the box - throws some errors.
Anyway, why not configure jest correctly. 

And with this change in useSelector it passes:

```ts
        if (options?.suspense) {
            // Note: Although it's not possible for an observable to be a promise, the selector may be a
            // function that returns a Promise, so we handle that case too.
            if (
                isPromise(value) ||
                (!value && isObservable(selector) && syncState(selector).isLoaded.get() === false)
            ) {
                if ((React as any).use) {
                    (React as any).use(value);
                } else {
                    if (isObservable(selector) && value === undefined) {
                        throw new Promise<T>((resolve) => {
                            syncState(selector).onChange(({ value }) => {
                                if (value.isLoaded) {
                                    resolve(selector.peek());
                                }
                            });
                        });
                    }
                    throw value;
                }
            }
        }

```

This is just one of the solutions.
For suspense to work it has to be thrown a promise.
From some reason the current implementation returns an undefined instead of promise. And I didn't see how I can access the original promise.
I wanted to fix it already in v2.
It is an important feature for us.

**Comment by jmeistrich** [comment]
Thank you for the test! I apparently did not understand suspense well enough when I’d originally written that 😅. It should be working now in alpha.5

Does this look right to you? We can return a Promise using when with the original selector. And I think the check for syncState shouldn’t actually be necessary? 

https://github.com/LegendApp/legend-state/blob/4d6cb89fb9364650363aaac868cf793c515e0c3a/src/react/useSelector.ts#L155

**Comment by lishine** [comment]
That is fun LOL with `when`. Seems to me that it replicates the internal promise, so it is like accessing the internal promise....
Seems like it will work.

**Comment by jmeistrich** [comment]
Awesome! Thanks a ton for all the details and test. I’m glad to have this working well :)
