### ISSUE TITLE
useComputed deps parameter v3

### ISSUE THREAD

**Issue by lishine** [LegendApp/legend-state#296]
Deps parameter should be after get function. Because it is related only to get function and it is monitored by react lint rule.
We set this rule to automatic - it auto fill the deps. useComputed has to be specified in eslint as an additional hook and it just works.

So currently my api on top of legend is this in v3:

```ts
import {
    useComputed as legendUseComputed,
    useSelector as legendUseSelector,
} from '@legendapp/state/react'
import type { DependencyList } from 'react'

export function useComputed<T>(compute: () => T | Promise<T>, deps: DependencyList): Observable<T>
export function useComputed<T, T2 = T>(
	compute: (() => T | Promise<T>) | ObservableParam<T>,
	set: (value: T2) => void
): Observable<T>
export function useComputed<T, T2 = T>(
	compute: (() => T | Promise<T>) | ObservableParam<T>,
	deps: DependencyList,
	set: (value: T2) => void
): Observable<T>
export function useComputed(param1: any, param2: any, param3?: any) {
	return legendUseComputed(param1, param3, param2)
}
```

**Comment by jmeistrich** [comment]
Interesting, I had thought react would want deps to be the last parameter. But I am actually planning to deprecate `useComputed` along with `computed` before the v3 release. They are now just wrappers around `observable(linked({ get, set })` if given a `set` or it’s just the same as `observable` if there’s only a get. I think it would be better to simplify the API down to fewer concepts.

I’m curious what you use deps for? I would like to make it work without deps, because creating new observables can be problematic if anything was subscribed to the old one - it would be better to trigger a recompute of the same observable so they are always stable. There may be an easier way to do that refreshing which I could build into useObservable, and knowing how you’re using it would help :)

**Comment by lishine** [comment]
Yes, I saw the thin wrapper. I like that it is simplified.
From my side - feel free to deprecate. 

You list here very good points.

The usage of observables in our app is either  through observe() or through .get() in react observer context. 
In case of observe(), currently when it's observable dependency change, dispose will be called and a new observe() will be created. That probably seems ok. 

But if o$.get() called in observer context and then  o$ gets recreated without unmounting component, then yes , it looks like a problem. 
So the solution should probably be - after creating new observable, to prune somehow the previous one - unsubscribe all it's subscribers. 
Actually no, I plane to leave the option to cache the observables instead of recreating.

Now, it is a good point about refreshing instead of recreating.  I remember now that I tried to do it with our Recoil wrapper, and either didn't work well or was conceptually wrong. 
I will look into this again. 

Ok, after a few thinking. Seems like refreshing should work only if no caching implemented. By caching I mean using same computed from several places instead of creating several computed (it will happen because computed created in a hook)

Ok, so in order to refresh I will need to create an observable alongside the main observable.
Your are right , an built in API will help.
Something like o$.refresh().
I don't use useObservable. I use observable only.

**Comment by lishine** [comment]
BTW about development. I import legend from another folder directly as a ts in a vite app and get a hot reload.

**Comment by jmeistrich** [comment]
I think I have a good solution which sets the deps array into an observable, which refreshes the created observable. That will let us use a deps array without creating a new observable when the deps change.

I’ll just test it a bit more and release an update shortly.

**Comment by lishine** [comment]
Great.
This is what I use for deps change detection:
```ts
/**
 * internal - comparison same as react useMemo
 */
export const areDepsEqual = (a: DependencyList, b: DependencyList) => {
	if (a.length !== b.length) {
		console.warn('useRecoilMemoSelector deps length changed between renders')
		return false
	}
	for (let i = 0; i < a.length; i++) {
		if (!Object.is(a[i], b[i])) {
			return false
		}
	}
	return true
}
```

**Comment by jmeistrich** [comment]
I just released alpha.4 which adds a deps array to `useObservable` and changes `useComputed` to be a light wrapper around `useObservable`. This refreshes the observable when the deps change rather than creating a new observable.

I am planning to deprecate both `computed` and `useComputed` but I’m leaving them for now as light wrappers around `observable` and `useObservable` to be backwards compatible. Observables are now reactive like computed if you just give them a function, so we don’t need a distinction anymore.

So I don’t think we should make a breaking change to `useComputed` since we’re going to deprecate it anyway. So the way to do `useComputed` with a deps array going forward will be to use `useObservable` with linked:

```ts
const state$ = useObservable(linked({
    get: () => …
    set: ({ value }) => …
}), [dep1, dep2])
```

How does that feel to you?

**Comment by lishine** [comment]
Thank you.
Checking.

Please look at the suspense isssue #295

**Comment by lishine** [comment]
It seems like the unification of computed and observable created some problem.

I have a wrapper for v2 which is fully working:

```ts
export function useParamComputed<P extends SerializableParam, T>(
	getFn: (param: P) => Observable<T>,
	deps: DependencyList
): ObservableComputed<(param: P) => Observable<T>>
export function useParamComputed<P extends SerializableParam, T>(
	getFn: (param: P) => T,
	deps: DependencyList
): ObservableComputed<(param: P) => ObservableComputed<T>>
export function useParamComputed<P extends SerializableParam, T>(
	getFn: (param: P) => T,
	deps: DependencyList,
	setFn: (param: P) => (t: T) => void
): ObservableComputed<(param: P) => Observable<T>>
export function useParamComputed<P extends SerializableParam, T>(
	getFn: (param: P) => T,
	deps: DependencyList,
	setFn?: (param: P) => (t: T) => void
): any {
	const _getFn = useHandler(getFn)
	const _setFn = useHandler(setFn ?? (() => () => {}))

	return reactUseMemo(() => {
		const map = new Map<string, ObservableComputed<T>>()
		return observable((k: P) => {
			const sk = JSON.stringify(k)
			const v = map.get(sk)
			if (v) {
				return v
			} else {
				const o$ = setFn
					? computed(
							() => _getFn(k),
							(value: T) => _setFn(k)(value)
					  )
					: computed(() => _getFn(k))
				map.set(sk, o$)
				return o$
			}
		})
		// eslint-disable-next-line @byondxr/automate/exhaustive-deps
	}, deps)
}
```

Now I have converted it to v3:

```ts
export function useParamComputed<P extends SerializableParam, T>(
	getFn: (param: P) => Observable<T>,
	deps: DependencyList
): Observable<(param: P) => Observable<T>>
export function useParamComputed<P extends SerializableParam, T>(
	getFn: (param: P) => T,
	deps: DependencyList
): Observable<(param: P) => Observable<T>>
export function useParamComputed<P extends SerializableParam, T>(
	getFn: (param: P) => T,
	deps: DependencyList,
	setFn: (param: P) => (t: T) => void
): Observable<(param: P) => Observable<T>>
export function useParamComputed<P extends SerializableParam, T>(
	getFn: (param: P) => T,
	deps: DependencyList,
	setFn?: (param: P) => (t: T) => void
): any {
	const _getFn = useHandler(getFn)
	const _setFn = useHandler(setFn ?? (() => () => {}))

	return useObservable(
		linked({
			get: () => {
				const map = new Map<string, Observable<T>>()
				return observable((k: P) => {
					const sk = JSON.stringify(k)
					const v = map.get(sk)
					if (v) {
						return v
					} else {
						const o$ = setFn
							? computed(
									() => _getFn(k) as any,
									(value: T) => _setFn(k)(value)
							  )
							: computed((() => _getFn(k)) as any)
						map.set(sk, o$ as any)
						return o$
					}
				})
				// eslint-disable-next-line @byondxr/automate/exhaustive-deps
			},
		}),
		deps
	)
}
```

Basically it is a useComputed with param. It is a function inside computed which return computed.
using:

```
const o$$ = useParamComputed((p:string)=>value)
const value = o$$.get()(param).get()
```

The problem that I am encountering right now is with typing . Runtime the above new  implementation with useObservable works fine.
So when I do o$$.get() I expect in return a type of function which returns an observable but instead I get in the example a map of string to number.

**Comment by jmeistrich** [comment]
I think what you’re creating there is actually built into v3. I called it a “lookup table”: https://legendapp.com/open-source/state/v3/usage/observable/#lookup-table.

I think you can remove all the extra logic and creating child observable/computed, and just use a lookup table that returns a linked?

```ts
export function useParamComputed<P extends SerializableParam, T>(
    getFn: (param: P) => T,
    deps: DependencyList,
    setFn?: (param: P) => (t: T) => void,
): any {
    const _getFn = useHandler(getFn);
    const _setFn = useHandler(setFn ?? (() => () => {}));

    return useObservable(
        (k: P) =>
            linked({
                get: getFn(k),
                set: ({ value }) => _setFn(k)(value),
            }),
        deps,
    );
}
```

**Comment by lishine** [comment]
https://stackblitz.com/edit/vitejs-vite-ism98j?file=src%2FApp.tsx

**Comment by jmeistrich** [comment]
Oh sorry, I forgot about that. I think you could actually just do that directly with useObservable. One of the changes in v3 is to ensure that children of observables are not observables, to prevent that chain of `get()` where the types are unclear. So I think you could implement that example as

```ts
import { observable } from '@legendapp/state';
import { observer, useObservable } from '@legendapp/state/react';

const o$ = observable({ a: 1, b: 2 } as Record<string, number>);

export const App = observer(() => {
  const c$$ = useObservable((p: string) => o$[p].get())

  return (
    <div>
      <div>{c$$[‘a’].get()}</div>
    </div>
  );
});

export default App;
```

**Comment by lishine** [comment]
That is some fast conversation LOL

First of all about the lookup.
I think I saw that , it is very cool.
My problem with it was that I want to be able to pass any stringifiable param, meaning for example to pass an object.
But ok, maybe I can enable this api for a string or a number.

I checked it and
It has some not obvious problems , basically you can see it does not work.
https://stackblitz.com/edit/vitejs-vite-mslr5c?file=src%2FApp.tsx

**Comment by lishine** [comment]
That last implementation with `useObservable` works indeed:
https://stackblitz.com/edit/vitejs-vite-2wj8u5?file=src%2FApp.tsx

**Comment by lishine** [comment]
Maybe observable operations can be extended with applying the parameter through a function like this:

```
const c$$ = useObservable((p: string) => o$[p].get())
const v = c$$('a').get()
```

Wouldn't it be cool? Seem to me doable isn't it?

**Comment by jmeistrich** [comment]
Ah good catch! `useObservable` with a deps array was not working with lookup tables (it wasn’t passing the parameter through). I’ll release a fix for that shortly.

What would that operation do? It would allow using an object as a key instead of a string? How would that work?

**Comment by lishine** [comment]
Yes, I need a way to allow using object as a key while providing typing as usual.
So one of the solutions was mine with the function inside: `o$.get()(param).get()`

Doing `o$[stringparam].get()` will not provide the solution because of js.
But what the lib doing under the hood? - it runs the function for each unique param and caches the observable in a map.
With `o$(param)`  it will do almost the same, just will stringify the param for accessing the map.
You can see the type of Serialazable Param above (it is how it was done in recoil)

**Comment by lishine** [comment]
Checked again the useObservable with param function and it does not work after adding dependecncies.
https://stackblitz.com/edit/vitejs-vite-2wj8u5?file=src%2FApp.tsx

**Comment by lishine** [comment]
New tests:
Second test fails.

```ts
    test('useObservable parameter function', () => {
        const obs$: Observable = observable({ a: 1, b: 2 });
        let value = 0;
        const Test = observer(function Test() {
            const obsLocal$ = useObservable((p: string) => {
                return obs$[p].get();
            });

            value = obsLocal$.a.get();

            return createElement('div', undefined);
        });
        function App() {
            return createElement(Test);
        }
        render(createElement(App));

        expect(value).toEqual(1);
    });

    test('useObservable parameter function with a deps array', () => {
        const obs$: Observable = observable({ a: 1, b: 2 });
        let value = 0;
        const Test = observer(function Test() {
            const obsLocal$ = useObservable((p: string) => {
                return obs$[p].get();
            }, []);

            value = obsLocal$.a.get();

            return createElement('div', undefined);
        });
        function App() {
            return createElement(Test);
        }
        render(createElement(App));

        expect(value).toEqual(1);
    });
```

**Comment by lishine** [comment]
Looks like another issue:
You set deps on each render thus trigerring update because deps array is new on each render...
You have to the equality check which I wrote above. 
https://github.com/LegendApp/legend-state/issues/296#issuecomment-2141391530

**Comment by lishine** [comment]
> Question: This test passes - 'useObservable with a deps array' Reading this code in `useObservable`
> 
> ```ts
>     if (depsObs$) {
>         depsObs$.set(deps! as any[]);
>     }
> ```
> 
> means that deps are set on each render thus trigerring update because deps array is new on each render... The `Object.is` deps equality check is not used. This can't work right.
> 
> So i don't understand how the test passes.

I understood why it is.
This is how legend actually works : upon setting observable with an array/object, it checks primitives recursively and disregards objects/arrays refs.

**Comment by lishine** [comment]
The original problem was addressed.
I created issues for the additional stuff.
