### ISSUE TITLE
ObservablePrimitive as a react component prop

### ISSUE THREAD

**Issue by lishine** [LegendApp/legend-state#30]
I have this simple Input from chakra, essentially a regular html input.
See the typescript problem.

![image](https://user-images.githubusercontent.com/6741645/194767838-4a6dffd7-e586-4c3b-aa92-fa1a9ed30def.png)

I tried to do this: 

```ts
defaultValue={value as unknown as string}
```

but still get this error in the console

![image](https://user-images.githubusercontent.com/6741645/194767906-8e0599e5-d790-457d-a2b4-8ddea4786c4e.png)

Running simple vite react project.

I am trying this project because of the hope that It could render components only once, similar to Solid.

**Comment by jmeistrich** [comment]
This is because it's an instance of an ObservablePrimitiveClass, not a string, and React can't handle observables in props. The easiest way to solve it is to call `.get()` to get the value from the observable.

```jsx
<Input defaultValue={value.get()} />
```

Alternatively you could wrap the Chakra input with `reactive` to give it reactive props. Then you could pass the observable to the reactive props (ending in $) like this:

```jsx
<Input defaultValue$={value} />
```

See https://legendapp.com/open-source/state/reactive-props/#make-external-components-reactive for more details of that, and let me know if it doesn't work or you have any more questions.

**Comment by lishine** [comment]
Thanks. I somehow missed that reactive props option...
(value.get() gets me again into that component rerendering land :( )

**Comment by jmeistrich** [comment]
@lishine Can you share a repo or a codesandbox? I can try to fix the types to work better with chakra.

**Comment by lishine** [comment]
Thanks.
Well, I created a nice vite codesandbox container, and it works fine...with types.
It is the same setup as my local vscode, but in local vscode all the the atributes of `ReactiveInput` are **any**
Will continue investigating...
shorturl.at/jLMS6

**Comment by lishine** [comment]
Though the reactive wrapper has some problem: I would guess chakra context not passing (the input field padding)
https://shorturl.at/jlpEU

**Comment by jmeistrich** [comment]
@lishine Did the links stop working? I looked at it an hour ago and just clicked it again and it just goes to the short url homepage.

**Comment by lishine** [comment]
[link](https://codesandbox.io/p/sandbox/awesome-stitch-lph063?file=%2Fsrc%2FApp.tsx&workspace=%257B%2522activeFileId%2522%253A%2522cl95kkaob001dluip2lke5s20%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cl96me2p900cq386j5yusv2g1%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl96me1d5009b386j8qo0h48u%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**Comment by jmeistrich** [comment]
@lishine The issue with chakra should be fixed in version 0.20.0. But please let me know if there's still any issues.

**Comment by lishine** [comment]
Great!

**Comment by eliperelman** [comment]
Unfortunately the codesandbox links don't see to be working anymore. Would you be able to re-share the recommended solution @jmeistrich? 🙌
