### ISSUE TITLE
bug(alpha + critical): Cant push to Vercel

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [LegendApp/legend-state#300]
I get an type error during next.js build time

![Screenshot_20240528_181439_Edge.jpg](https://github.com/LegendApp/legend-state/assets/77451351/0e496311-ff3f-4447-8813-86363f182d8f)

**Comment by FleetAdmiralJakob** [comment]
Better explanation of the bug here: #301

**Comment by jmeistrich** [comment]
This should be fixed in `alpha.2`. And it’s the same as #301 so I’ll close this in favor of that one, which I’m just leaving open until it’s confirmed fixed.
