### ISSUE TITLE
How to debounce

### ISSUE THREAD

**Issue by lishine** [LegendApp/legend-state#33]
How to debounce without rerendering the component?
This does not work, 'debounceLodash' printed only once, though value is changing:

```ts
	const value = useObservable(props.defaultValue ?? '')
	const ref = useRef(
		debounceLodash(() => {
			console.log('debounceLodash')
			props.onChange(value.get())
		}, 200)
	)
	useObserve(ref.current)
```

**Comment by jmeistrich** [comment]
The `value.get()` needs to be called within the context of the observe, but I think that would have it get called within the debounce instead, so it doesn't set up the tracking. I'm not sure exactly what you're going for, but I think this might work:

```js
useObserve(() => {
    const val = value.get()
    debounceLodash(() => {
        console.log('debounceLodash')
	props.onChange(val)
    }, 200)
})

```

**Comment by lishine** [comment]
So the .get() will not work in setTimeout...

This solution is working
https://shorturl.at/jlpEU

**Comment by jmeistrich** [comment]
@lishine That link seems to be broken

**Comment by lishine** [comment]
[link](https://codesandbox.io/p/sandbox/awesome-stitch-lph063?file=%2Fsrc%2FApp.tsx&workspace=%257B%2522activeFileId%2522%253A%2522cl95kkaob001dluip2lke5s20%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522key%2522%253A%2522cl96me2p900cq386j5yusv2g1%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl96me1d5009b386j8qo0h48u%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D)

**Comment by jmeistrich** [comment]
I'll close this since I think it's solved, but let me know if I missed something.
