### ISSUE TITLE
issue with typescript strict mode and observable primitives

### ISSUE THREAD

**Issue by chrisjfunk** [LegendApp/legend-state#34]
when exporting an observable from a module typescript (strict mode) complians about not being able to name used types

ie 
export const valid = observable(true)

gives the below error:

![image](https://user-images.githubusercontent.com/18413/195460382-c8cbe6db-42db-400e-a902-a973dad6b8aa.png)

exporting the types makes this error go away:

**export** interface ObservablePrimitiveFnsBase<T> extends ObservableBaseFns<T> {
    set(value: T | ((prev: T) => T)): ObservablePrimitiveChild<T>;
}
**export** interface ObservablePrimitiveFnsBoolean<T> {
    toggle(): T;
}

**Comment by jmeistrich** [comment]
We've done a lot of improvements to the types recently so hopefully this is fixed? Are you still having this issue as of `0.21.18`? If so can you share some more code of the error?

**Comment by danstepanov** [comment]
@jmeistrich am I missing something here? see line 7 https://snack.expo.dev/@danstepanov/no-service-hook?&platform=mydevice

**Comment by jmeistrich** [comment]
@danstepanov It seems like Expo Snack has a problem with nested dependencies: https://github.com/expo/snack/issues/60

I'm not sure how to handle that. After some research I can't figure out how to solve that issue in Expo...

We have a lot of nested dependencies outside of the core for React stuff, helpers, hooks, etc... which I think is good to keep the imported size down if you don't use all of the features. In the future I'd like to support other libraries so `/react` wouldn't necessarily be imported. So I don't think we should change the way we're exporting, at least for now.

Also I noticed you're using version 0.19 there - you may way to upgrade to the latest version `1.2.8`.
