### ISSUE TITLE
v3 + indexedDB => Type Error

### ISSUE THREAD

**Issue by luudv** [LegendApp/legend-state#357]
I am using V3 combined with indexedDB persistence. Everything seems to work smoothly, but sometimes I get 502 error. I check the log and the system reports this error.
<img width="1104" alt="2024-09-05_9-23-57 AM" src="https://github.com/user-attachments/assets/c7935cb9-d572-4b86-9cb5-3fe47656cdbe">

**Comment by jmeistrich** [comment]
Is that running on a server? You may need to make sure that you're only persisting when running in the browser. I'll add a better error message for that.

**Comment by darklight9811** [comment]
@jmeistrich what is the proper way to handle SSR in those cases?
