### ISSUE TITLE
I started a demo with Create-react-app, and for some reason, it didn't work

### ISSUE THREAD

**Issue by a554878526** [LegendApp/legend-state#36]
<img width="611" alt="image" src="https://user-images.githubusercontent.com/70568691/195523800-469d013f-c2c9-4532-9413-76c4bdce23d6.png">

<img width="998" alt="image" src="https://user-images.githubusercontent.com/70568691/195523645-d8c81e4f-577e-4235-90cd-0354cb3aba68.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/70568691/195523905-6bf27759-8384-4518-8267-0ff5d7df85e3.png">

**Comment by jmeistrich** [comment]
You just need to call `enableLegendStateReact()` to enable rendering observables directly. See https://legendapp.com/open-source/state/react-basics/#rendering-directly

**Comment by a554878526** [comment]
https://github.com/LegendApp/legend-state/issues/36#issuecomment-1277134249


Thank you for your wonderful reply. Thank you. Your library looks great!

**Comment by jmeistrich** [comment]
I'm going to change it in the next version to enable it when anything is imported from the `/react` export so that should be easier :)
