### ISSUE TITLE
[Question] Is there a way to convert an observable to a normal React state?

### ISSUE THREAD

**Issue by pgpmnesx** [LegendApp/legend-state#364]
Hi Jay, 
As I mentioned in the title, sometimes I need to pass arguments to other hooks. If we have an API like `convertToState(ob$)` or `ob$.toState()`, it's really useful instead of wrapping the whole component with `observer`.
Thank you.

**Comment by jmeistrich** [comment]
You can use [useSelector](https://www.legendapp.com/open-source/state/v3/react/react-api/#useselector) to get the value to pass to other hooks, and you can pass `obs$.set` as the set function.

Making a hook to wrap that up nicely could be interesting... Would anyone else want that?
