### ISSUE TITLE
Observable with syncedCrud is pushing two duplicate records when inserted single

### ISSUE THREAD

**Issue by AbhieShinde** [LegendApp/legend-state#366]
Here's my observable declaration
```
export const profile$ = observable<Profile[]>(
	syncedCrud({
		initial: [],
		as: "array", // the observable will be an array
		list: async (params: SyncedGetParams<object>) => {
			const { data, error } = await serverGetProfile(params);
			if (error) {
				// Handle error, throw an Error to trigger a retry
				return null;
			} else if (data) {
				console.info("list", data);
				return data;
			}
			return null;
		},
		create: async (input, params) => {
			const { data, error } = await serverCreateProfile(input, params);
			if (error) {
				// Handle error, throw an Error to trigger a retry
			} else if (data) {
				console.info("create", data);
				return data;
			}
		},
		update: async (input, params) => {
			const { data, error } = await serverUpdateProfile(input, params);
			if (error) {
				// Handle error, throw an Error to trigger a retry
			} else if (data) {
				console.info("update", data);
				return data;
			}
		},
		delete: async ({ id }: { id: number }, params) => {
			const { data, error } = await serverDeleteProfile(id, params);
			if (error) {
				// Handle error, throw an Error to trigger a retry
			} else if (data) {
				console.info("delete", data);
				return data;
			}
		},
		onSaved: ({ saved, input, currentValue, isCreate, props }: any) => {
			console.info("onSaved", saved, input, currentValue, isCreate);

			return saved;
		},
		transform: {
			load: (value, method) => {
				console.info("transform load", value, method);
				return "set" == method ? value : value;
			},
			save: (value) => {
				console.info("transform save", value);
				return value;
			},
		},
		mode: "merge", // Merge the data from the server with the local data on initial load
		updatePartial: true, // Update with only changed fields
		fieldCreatedAt: "created_at",
		fieldUpdatedAt: "updated_at",
		fieldDeleted: "is_deleted", // soft delete
		changesSince: "last-sync", // Only get changes since last sync / Sync only diffs
		persist: {
			plugin: storagePlugin,
			name: "profiles",
			retrySync: true,
		},
		retry: {
			infinite: true, // Retry changes with exponential backoff
		},
	}),
);
```

And here's my observer component
```
export const Profile = observer(function App() {
	const profile = profile$.get();

	const onClickClear = () => profile$.set([]);

	const onClickInsert = () => {
		const profiles = [
			...profile,
			{
				id: profile.length + 1,
				name: `Profile ${profile.length + 1}`,
				// Do not set created_at here, otherwise it will be considered as an update operation
			},
		];

		profile$.set(profiles);
	};

	return (
		<View>
			<Button title="Clear" onPress={() => onClickClear()} />
			<Text> </Text>
			<Button title="New" onPress={() => onClickInsert()} />
			<Text> </Text>
			{profile.map((profile, i) => (
				<View key={i}>
					<Text>ID: {profile.id}</Text>
					<Text>
						Name:{" "}
						{profile.name
							? profile.name
							: /* @ts-ignore */
							  `${profile.first_name} ${profile.last_name}`}
					</Text>
					<Text>Created at: {profile.created_at}</Text>
					<Text>Updated at: {profile.updated_at}</Text>
					<Text> </Text>
				</View>
			))}
		</View>
	);
});
```

What am I doing wrong here that causes a `New` button to add two duplicate records with the same ID?

Upon debugging into this, I found out that both `create()` and `onSaved()` are returning the values that are being pushed into an observable state, but upon removing the `onSaved()` or by NOT returning anything from `create()` I'm getting errors.
What should be the workaround for this so that only one object will be pushed into the state?

https://github.com/user-attachments/assets/a1274d94-6f8d-437c-9ad5-0b575e3f8a11

**Comment by AbhieShinde** [comment]
#### When I remove the `onSaved()`, I'm getting this error,

![image](https://github.com/user-attachments/assets/22ddf152-e397-43f5-9452-4a76f17d8f50)

**Comment by jmeistrich** [comment]
That error is because you're rendering these dates directly in React. You'd want to convert those to strings.

```js
<Text>Created at: {profile.created_at}</Text>
<Text>Updated at: {profile.updated_at}</Text>
```

And it seemed there was an error caused by returning `saved` directly from `onSaved` - I've always returned either a modified object or nothing from that so I didn't catch that, thanks!

Also one thing that might be confusing is you named both the array and the individual items "profile".

**Comment by AbhieShinde** [comment]
To resolve this, I stopped returning anything from `create()`, which eventually made `onSaved()` NOT called at all, so I removed the `onSaved()` block.

**Comment by AbhieShinde** [comment]
Hi @jmeistrich 
I am reponing this because consider a scenario where I'm just adding a new object into an observable state with required values and from `create()` I get the full object with DB inserted values for it (like ID, created_at, etc.), and as mentioned earlier if I do not return anything from `create()` the observable state will not update and will only have values which are inserted from the UI.
So when I returned the updated object, the original issue came up again by creating two records in the observable state, 1. which is inserted from the component, and 2. inserted by `create()` which only has these values `{ ID: 123, created_at: 'timestamp' }`.

How can I make sure that when a server call from the `create()` is completed, then the return value merges with the object from the observable state for which this sync has happened? Or any other workaround for this?

**Comment by AbhieShinde** [comment]
Here's my observable state declaration,

```
		create: async (input: Profile, params: SyncedSetParams<object>) => {
			const { data, error } = await serverCreateProfile(input, params);

			if (error) {
				// Handle error, throw an Error to trigger a retry
			} else if (data) {
				console.info("created:", data);
				return data;
				// Upon returning the data here, the observable will have new record with it, which leads to duplicate records with same id
			}
		},
		onSaved: ({ saved, input, currentValue, isCreate }) => {
			console.log("onSaved", saved, input, currentValue, isCreate);
			return {
				id: saved.id,
				created_at: isCreate
					? saved.created_at
					: currentValue.created_at,
				updated_at: isCreate
					? saved.created_at
					: currentValue.created_at,
			};
		},
                updatePartial: true,
		fieldDeleted: "is_deleted",
		changesSince: "last-sync",
		persist: {
			plugin: persistStorage,
			name: "profiles",
			retrySync: true,
		},
```
The insert handler,
```
	const onClickInsert = () => {
		const newProfiles = [
			...profiles,
			{
				id: profiles.length + 1,
				first_name: "Profile",
				last_name: `${profiles.length + 1}`,
				avatar: `https://reqres.in/img/faces/${
					profiles.length + 1
				}-image.jpg`,
				email: `profile${profiles.length + 1}@example.com`,
				// Do not set created_at here, otherwise it will be considered as an update operation
			},
		];

		profiles$.set(newProfiles);
	};
```
And when I insert a new object from the observed component using above handler, as mentioned in previous comment, two new objects are inserted into observable state like this,

<img width="727" alt="image" src="https://github.com/user-attachments/assets/83ef262d-82dd-444b-b493-5f436cd673ff">

Instead, I just local state to have only one new object with all the values merged returned by `onSaved()`, how can I do that?

@jmeistrich please help me out with this.

**Comment by AbhieShinde** [comment]
@jmeistrich it seems like this is an issue only with an array data type.
`as: "array"`
