### ISSUE TITLE
syncedCrud() NOT syncing all offline changes to remote

### ISSUE THREAD

**Issue by AbhieShinde** [LegendApp/legend-state#367]
Steps to reproduce,
1. Use an **array** as a data type for the observable state. `as: "array",`
2. Open the app, and load the `observer` component, so the local state will have server data
3. Go **offline**, and add multiple records to this array. I'm doing it in this way `.set((prev) => [...prev, ...newProfiles])`
4. Now go back **online**
5. Wait for the `delay`, and now **only the last element** will get synced to the server using `create()`, and all other new elements that are added before the last element remains only in local storage.

```
syncedCrud({
		initial: [],
		as: "array",
		list: async (params: SyncedGetParams<object>) => {...},
		create: async (input: Profile, params: SyncedSetParams<object>) => {
			const { data, error } = await serverCreateProfile(input, params);

			if (error) {
				throw error;
			} else if (data) {
				console.info("created:", data);
			} else {
				throw new Error("Failed to create profile");
			}
		},
		update: async (input: Profile, params: SyncedSetParams<object>) => {...},
		mode: "merge",
		updatePartial: true,
		fieldCreatedAt: "created_at",
		fieldUpdatedAt: "updated_at",
		fieldDeleted: "is_deleted",
		changesSince: "last-sync",
		persist: {
			plugin: persistStorage,
			name: "profiles",
			retrySync: true,
		},
		retry: {
			infinite: true,
		},
	}),
```

Thanks! @jmeistrich 

> Using version: `3.0.0-beta.8`

**Comment by jmeistrich** [comment]
Can you try just pushing to the array? Like `obs$.push(newProfile`. It might be that the cloning is messing it up. 

The "array" option is generally not as stable for mutations. I almost didn't support it at all... It's possible there's some cases that don't work - I'll add more tests and see if I can find anything breaking.

And I should probably add more to the docs about it. But basically when create and update return from the server it's harder to know which element in the original observable. It has to iterate the array to find the changed element and apply the change to it. That may not be working perfectly... I'll check on that.

For your usage I'd suggest using `as: 'object'` or `as: 'Map'`. It's much easier to modify by id - you can just update `obs$[id].text.set('...')` for example.

**Comment by subhendupsingh** [comment]
I have the same problem. Steps:
1. Open the todos in different browsers
2. Go offline and delete some todos (soft delete with last-sync), legend tries to sync saying connection error 2-3 times.
3. Come back online, no more retries. Both the browsers and the db go out of sync.

**Comment by jmeistrich** [comment]
@subhendupsingh Just to confirm, you're using `as: "array"` too? I'll writes some more tests for that and see what problems I can find.

**Comment by subhendupsingh** [comment]
No `as` property is default which i guess is object. Here is my exact configuration

```typescript
const store$ = observable(syncedSupabase({
        supabase: db,
        collection: 'todos',
        // Optional:
        // Select only id and text fields
        select: (from) => from.select('id,text,completed,deleted,updated_at,created_at,row_id'),
        // Filter by the current user
        //filter: (select) => select.eq('user_id', id),
        // Don't allow delete, we will use soft deletes
        actions: ['read', 'create', 'update'],
        // Realtime filter by user_id
        realtime: true,
        // Persist data and pending changes locally
        persist: { name: 'todos', retrySync: true, plugin: ObservablePersistLocalStorage },
        // Sync only diffs
        changesSince: 'all',
        retry: {
            infinite: true,
        },
        fieldDeleted: 'deleted',
        fieldCreatedAt: 'created_at',
        fieldUpdatedAt: 'updated_at',
        fieldId: 'id',
        subscribe({refresh, update, lastSync}) {
            //console.log({refresh, update, lastSync});
            refresh();
        },
        onError(error, params) {
            console.error(error, params);
        },
    }));
```

**Comment by AbhieShinde** [comment]
Thanks @jmeistrich, `obs$.push(newProfile)` resolved the issue for me on native platforms but on the Web with _localStorage_ as a persist plugin, even after **successful** `create()` execution, the browser keeps on sending `create()` requests infinitely, seems like it's not clearing the `pending` stuff from the _localStorage_ properly.

**Comment by hirvesh** [comment]
@jmeistrich - I am observing the same behaviour as well, using as=object and when I go offline and add multiple items and come back online, only the last one is synced.

**Comment by jmeistrich** [comment]
Ah yikes ok, I've got a repro in a test. My other tests did multiple creates at once but it's a problem with subsequent creates coming in later. Working on it!

**Comment by hirvesh** [comment]
You are the best @jmeistrich - thank you! 👌💪🙏🫡

**Comment by hirvesh** [comment]
I tested the commit within my app and I can confirm that now all local offline changes get synced correctly 🥳

**Comment by jmeistrich** [comment]
This should be fixed in beta.14. But please let me know if it's not working perfectly!
