### ISSUE TITLE
V3+TypeScript: Custom reactive components still demand unprefixed props

### ISSUE THREAD

**Issue by BorisZubchenko** [LegendApp/legend-state#371]
The example is taken [from the docs](https://legendapp.com/open-source/state/v3/react/fine-grained-reactivity/#reactive):
```tsx
import { observable } from "@legendapp/state";
import { reactive } from "@legendapp/state/react";

const isSignedIn$ = observable(false);

const Component = reactive(function Component({ message }: {message: string}) {
  return <div>{message}</div>;
});
```
![image](https://github.com/user-attachments/assets/3e59721c-b424-45ea-8dbc-81bc749a31a4)
The `message` prop should be omitted in favor of `$message`

**Comment by jmeistrich** [comment]
Thank you! This should be fixed in beta.9. But please let me know if it's still not looking right.
