### ISSUE TITLE
V3: reactiveComponents example with Framer Motion raises TypeScript errors

### ISSUE THREAD

**Issue by boar-is** [LegendApp/legend-state#374]
Following[ the example from the docs](https://www.legendapp.com/open-source/state/v3/react/fine-grained-reactivity/#reactivecomponents):
```ts
import { reactiveComponents } from "@legendapp/state/react";
import { motion } from "framer-motion";

const ReactiveMotion = reactiveComponents(motion);
```
raises the following TypeScript error:
![image](https://github.com/user-attachments/assets/4db9a2eb-435c-44cf-bbfc-36d7e039933d)

**Comment by jmeistrich** [comment]
Ah thanks! I improved the types of `reactive` recently which looks to have broken that. It seems like this is the easy fix, to change `FC` to `any`:

```ts
declare function reactiveComponents<P extends Record<string, any>>(components: P): ObjectShapeWith$<P>;
```

I'll release this fix in the next update (which is a bit big with improvements to a bunch of sync things).
