### ISSUE TITLE
Set isn't observable

### ISSUE THREAD

**Issue by dominictobias** [LegendApp/legend-state#379]
```ts
const fileNames = useObservable<string[]>([])

const fileNamesSet = useObservable(() => new Set(fileNames.get()))

useObserve(() => {
    console.log('fileNames changed', fileNames.get())
})

useObserve(() => {
  console.log('fileNamesSet changed', fileNamesSet.get())
})
```

`'fileNamesSet changed'` isn't triggered even if `'fileNames changed'` changed.

Are Maps and Sets not supported?

**Comment by jmeistrich** [comment]
Ah oops! It's working fine for Set functions like add/delete etc... but it wasn't notifying of changes correctly if setting a `new Set`. I've fixed it and it will be in the beta.14 release. I'll probably do that release later today, I'm working on some changes to onError and want to make sure it's solid before releasing it.

**Comment by jmeistrich** [comment]
Should be fixed in beta.14. But please let me know if you still see any issues.

**Comment by dominictobias** [comment]
Nice, thanks!
