### ISSUE TITLE
Docs: Removing property from observable with delete()

### ISSUE THREAD

**Issue by ckruppe** [LegendApp/legend-state#38]
I try to create an observable state with dynamic properties.
Adding an new property to the observable works like a charm but removing is not possible.
Is there a way to remove properties from an observable after it was set?

**Comment by jmeistrich** [comment]
You can call `delete()` on any observable to delete it. So you can do `obs[key].delete()` to delete a property from an observable.

**Comment by ckruppe** [comment]
Nice thanke you very much. :) Did not find any information to that on your docs.
Btw. your state lib is awesome.

**Comment by jmeistrich** [comment]
Good point! We should add that to the docs.
