### ISSUE TITLE
Supabase observables show incorrect types

### ISSUE THREAD

**Issue by drewlyton** [LegendApp/legend-state#380]
When using the `syncedSupabase` plugin, the final observable does not show the correct type based on the `select()` query builder.

![SCR-20241030-pavf](https://github.com/user-attachments/assets/601e63aa-1839-4a2c-9a03-25c9956c2305)

Also, the `select` parameter throws an error unless I put `*` in the string.
![SCR-20241030-patb](https://github.com/user-attachments/assets/f9fba74f-cd9a-4161-bd9d-d8167e680019)

![SCR-20241030-pbbt](https://github.com/user-attachments/assets/5959a819-aa22-46fb-a647-9b2d3b6a0b10)

I feel like the returned type should just match what the supabase JS client would return. For example:
![SCR-20241030-peto](https://github.com/user-attachments/assets/ea8531c2-62b4-417c-8f4d-a57a5d32a404)

**Comment by jmeistrich** [comment]
This should be fixed in beta.14. That's pretty cool! I hadn't known that the supabase client extracts keys from select like that :)
