### ISSUE TITLE
How to rollback onError

### ISSUE THREAD

**Issue by catalinmiron** [LegendApp/legend-state#382]
I'm using `syncedSupabase` and I would live to rollback the changes when transaction fails (onError). Is there an automatic way of doing it?

**Comment by jmeistrich** [comment]
Oh that's a great idea! I'm working on revamping onError right now so I'll look at adding that.

**Comment by jmeistrich** [comment]
beta.14 makes some big changes to `onError`, one of which is a `revert()` function. But it's still in progress - it currently reverts all of the changes in the batch whereas it should revert only the ones that errored. I'll aim to fix that in beta.15. But for now if you want to play with it please let me know if it works well?

**Comment by jmeistrich** [comment]
Ok done! The revert function in beta.16 should be correct, rolling back only the change that caused the error. Please let me know if it isn't working right.

**Comment by catalinmiron** [comment]
@jmeistrich just tested it, everything works as expected! Thanks for fast response!

What do you think about returning `.errors` along with `changes` on the $ when there's a revert or `throw new Error()` happening?
