### ISSUE TITLE
Accessing value before set gives the set value

### ISSUE THREAD

**Issue by kieran-osgood** [LegendApp/legend-state#4]
Hey! I caught the stream with Jamon and wanted to take a look out of interest as I was keen to see how adding the run time type checking with zod via a plugin of some kind might go 👀 

I wasn't sure if I've missed something in the docs, but if you see the below, I tried logging out the value prior to setting and it seems to give me the set value?

** Note ** - it gives the correct value if I call `console.log("beforeSet", user.get());`

https://codesandbox.io/s/mystifying-darkness-byq4gx?file=/src/App.tsx:0-848

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/17687552/190243254-c1bccffc-88f1-48cb-a84d-da11e4826a56.png">

```
import "./styles.css";
import { observable } from "@legendapp/state";
import { enableLegendStateReact } from "@legendapp/state/react";
import { z } from "zod";
enableLegendStateReact()
// const __DEV__ = true;
const User = z.object({
  name: z.string().nullable()
});
type zUser = z.infer<typeof User>;

const user = observable<zUser>({
  name: null
});

export default function App() {
  const onPress = () => {
    console.log("beforeSet", user);
    user.set({name: "my new name"});
  };
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      <button onClick={onPress}>Update that username!</button>
      <p>username: {user.name}</p>
    </div>
  );
}
```

**Comment by jmeistrich** [comment]
This is just a quirk of the Chrome devtools because it evaluates `console.log` of Proxy lazily. So since you set it to the new name immediately, by the time you see it in the devtools the object through the Proxy has the new name. When you log the raw object from `get()` it evaluates the object immediately so it shows the current value before the set. That does look pretty weird though 😂

**Comment by kieran-osgood** [comment]
Thanks for confirming, had a feeling it might be but I was just looking at it like....wut? lets go check

Just wanna add - awesome work on this library! 
Very excited to put it into play, have held off on touching any new state libs for the last 18 months sticking with mobx-state-tree, got very tempted with valtio but didn't like the snapshot stuff - you've managed to package up everything I had looked for and more (like who knew you could atomise re-renders down to such a small level)

Well Done 👏🏼
