### ISSUE TITLE
syncedSupabase: select clause from syncedSupabase is providing only 1000 records from the remote supabase

### ISSUE THREAD

**Issue by puneethkumar-v** [LegendApp/legend-state#408]
Hi,
I'm facing this issue while using syncedSupabase plugin on react native, there are 13K+ of records in the remote supabase but when fething using select clause, I'm only getting max of 1000 records, is there any limit while fetching the data from the remote db.

Following the code setup:

```js
const customSynced = configureSynced(syncedSupabase, {
  persist: {
    plugin: observablePersistAsyncStorage({
      AsyncStorage,
    }),
  },
  generateId,
  supabase,
  changesSince: 'last-sync',
  fieldCreatedAt: 'created_at',
  fieldUpdatedAt: 'updated_at',
  fieldDeleted: 'deleted',
});


const _todos$ = observable(
  customSynced({
    supabase,
    collection: 'todos',
    select: (from) => from.select('*'),
    actions: ['read', 'create', 'update', 'delete'],
    realtime: true,
    persist: {
      name: 'todos',
      retrySync: true,
    },
    retry: {
      infinite: true,
    },
    subscribe({refresh, update, lastSync}) {
      console.log("REFRESH", {refresh, update, lastSync});
      refresh();
    },
    onError(error, params) {
      console.error("ERROR", error, params);
    },
  })
);

  console.log('todos', todos && Object.values(todos)?.length)
```

When I use limit() function on select clause like this:

```js
    select: (from) => from.select('*').limit(50)
```

this works, it give me only 50 records from the db, but when I try to set the limit to 5000, it only provides me 1000 records, why is this happening

Exact scenario tried:

Initially while on the offline, I have uploaded a csv file containing 13k+ records of todo, it was uploaded successfully, then running my app, on the initial load, it fetched only 1000 records instead of 13K+ records

**Comment by puneethkumar-v** [comment]
Found Solution:

It isn't related to Legend State, there was a max limit in the supabase, that can be changed to whatever number user wants

**Comment by jmeistrich** [comment]
Ah ok, since this isn't a Legend State problem I'm close the issue. Or is there something Legend State can do better for this?
