### ISSUE TITLE
Improve typing of `item` in `For` component

### ISSUE THREAD

**Issue by Manc** [LegendApp/legend-state#42]
I'm not quite sure why, but the TypeScript typing of the item argument inside the `For` component seems to not recognise the type of the list as provided to the `each` argument.

Screenshot taken from my [example](https://codesandbox.io/s/legend-w-observable-forked-mjsd91?file=/src/App.tsx:1992-2018):

<img width="1176" alt="Screenshot 2022-10-17 at 12 23 35" src="https://user-images.githubusercontent.com/811578/196165015-4557c973-7af2-4ecf-b7e6-d00eb8be577d.png">

**Comment by Manc** [comment]
I may give it a try soon. It's probably best to familiarise myself a bit more with the whole concept first.

**Comment by Manc** [comment]
Just to give you an update, today I made an attempt to improve typing with TypeScript strict mode (I always use strict mode in my projects as it massively helps to avoid runtime errors). Unfortunately I don't have a presentable result yet as a lot of code in this library is not strongly typed and me being still new to it, I find it difficult to figure out what some of the code actually does.

Just to give you an example: There are many TS (strict) errors in `observable.ts`. The type for `NodeValue` is defined as follows:
```TS
export interface NodeValue {
    id: number;
    parent?: NodeValue;
    children?: Map<string | number, NodeValue>;
    proxy?: object;
    key?: string | number;
    isActivatedPrimitive?: boolean;
    root: ObservableWrapper;
    listeners?: Set<{ track: TrackingType; noArgs?: boolean; listener: ListenerFn }>;
}
```

But then, in code where `NodeValue` objects are being used, optional properties like `key` are regularly being used as if they could not be `undefined`, so I don't know whether (in this example), `key?:` should actually be `key:` or if using the `key` value is indeed dangerous and code should be changed to protect against it.

Generally, my idea would be to strengthen typesafety step by step leaving the strict mode setting turned off for the time being (unless whilst working on this). I wanted to start with some easy parts to get into the whole thing and then, of course, the work on the `For` component. The thing with the React component turned messy. I made sure the tests run, but I also changed them slightly (I didn't change what the test actually do, but made them a bit more verbose and explicit in terms of types and definitions within them).

If you're interested, you can take a look, what I've done [here](https://github.com/Manc/legend-state/tree/experiment), but this is by no means pull request worthy. Although I'd love to help, I'm not sure how much time I can spend on this. Anyway, I'll let you know if I make any progress.

**Comment by jmeistrich** [comment]
Thanks! This is great! I'm learning a lot from your changes. I agree that it would go good to strengthen it step by step. We can pull in just a couple commits at a time if you want?

NodeValue is a bit weird because the root node does not have a parent or a key, but every other node does. It may be better to have the root node be a different type so all the other nodes can be typed more strongly?

**Comment by Manc** [comment]
Thank you for your feedback. I made a few more changes. I would have loved to make individual small changes that I could submit as pull requests, but since I'm messing around with many parts of the library that all work together, I touched many parts at once. So for now, it's still a bit of a mess, I'm afraid.

A few notes/explanations regarding my changes so you better understand what I was doing:

- [[a61f69b](https://github.com/Manc/legend-state/commit/a61f69b3685ca147918c1db1aabd06fcd1005d3c)]: I converted `ObservablePrimitiveClass` to an actual `class` as I was getting a TS error with `new ObservablePrimitiveClass()`. To be honest, I'm not familiar with `Object.defineProperty()`, so I left those parts as they were and moved the regular functions into the class.
- [[a61f69b](https://github.com/Manc/legend-state/commit/a61f69b3685ca147918c1db1aabd06fcd1005d3c)]: Just a few (hopefully) simplifications on the type checking helper functions. I even did a [benchmark](http://jsben.ch/k0i2S) on the `isBoolean` and it looks like a regular `typeof` is the fastest.
- [[af05b7d](https://github.com/Manc/legend-state/commit/af05b7d4e6a11bdca4afe5a1eb422a217ed5df13)]: I added a whole new test file for my own experiments and made a range of little changes, mostly regarding typing. I think the only minor change is in `function createObservable`, where instead of changing/reusing/altering the argument variable, I added a `const valueIsPromise` and change a few lines accordingly. I think code becomes slightly easier to read and makes typing easier.

All in all, I think I'm getting a bit closer to getting types a bit tighter, but my main problem at the moment is that "dotting through" properties that may or may not exist in in an Observable, like being able to call `obs.test.test2.test3.set(1)` even if e.g. `test2` is undefined. It's brilliant how you do this, but I don't understand how this is being achieved. Somehow with the nodes and Proxy object and its getter function or something. I think it would be great if we could find a way to make this work properly with TypeScript.

Currently, depeding whether TS strict mode is on or off, type checks fail at different places. You will see this if you look at my [experiments.test.ts](https://github.com/Manc/legend-state/blob/experiment/tests/experiments.test.ts).

**Comment by jmeistrich** [comment]
Awesome, these changes make sense to me. Just one issue:

[[a61f69b](https://github.com/Manc/legend-state/commit/a61f69b3685ca147918c1db1aabd06fcd1005d3c)]: I'd rather leave it as not a class - I actually converted it from a class a little while ago because it's smaller and faster as a prototype object (please correct me if I'm wrong). But I think it's possible to export its type as if it's a class? I think I saw that in another library - I can look into that more.

Yes, dotting through works because of the Proxy, and you can actually dot through any path and it will work fine. The types work using `Recurse` defined in `observableInterfaces.ts` to extend the object properties with the observable functions - that works well enough in non-strict mode but maybe needs more massaging for strict mode?

Would you like to tighten up the changes as they are and we can merge them, and then continue with further improvements? Or keep going fixing up more and more? I'm also happy to step in any work on any particular thing you don't have the full context on?

**Comment by Manc** [comment]
Regarding the class: You're absolutely right – keep it a prototype object. I had no idea and the only reason I changed it was, because it *seemed* cleaner, but since this library is all about performance, I agree with you.

I have been busy integrating the library into my project. I think it's quite important, because I'm still learning a lot about it whilst working with it in a real project. I will try to clean up a few things and then, maybe I can make a few individual pull requests.

**Comment by prbxr** [comment]
#47

**Comment by jmeistrich** [comment]
@Manc How are things going? I want to start making some improvements to strict mode soon and I would love to use a PR from you as a starting point if you'd like? We can do it one commit at a time if you had large changes that weren't finished?

**Comment by jmeistrich** [comment]
Closing this issue in favor of a larger discussion of strict types in https://github.com/LegendApp/legend-state/discussions/53
