### ISSUE TITLE
onSaved is not being called for syncedCrud as Map 

### ISSUE THREAD

**Issue by AbhieShinde** [LegendApp/legend-state#422]
When using an observable as "Map," the `onSaved()` method is NOT being called due to incorrect value accessing. For more details, see https://github.com/LegendApp/legend-state/pull/421

**Comment by jmeistrich** [comment]
Thanks for the fix! I merged the PR and will release an update soon.

**Comment by AbhieShinde** [comment]
Thanks, I confirmed this is working as expected with `v3.0.0-beta.20`.
