### ISSUE TITLE
Missing Legend.path

### ISSUE THREAD

**Issue by hckhanh** [LegendApp/legend-state#44]
I think there are some missing tag for SVG's tags.

**Comment by jmeistrich** [comment]
Oh yes, I'll add those tags. They should actually work even though the types are missing. But I'll release an update with them included in the types tomorrow.

**Comment by jmeistrich** [comment]
It's fixed in version `0.21.1-next.1` if you want to try it now, but I'll release a normal update tomorrow (after finishing testing a change to `useComputed` I was working on).

**Comment by hckhanh** [comment]
Thank you @jmeistrich, I will try it now.

**Comment by jmeistrich** [comment]
Fixed in `0.21.1`. Let me know if you have any further issues with it.
