### ISSUE TITLE
React Native - auth and guest stacks

### ISSUE THREAD

**Issue by rares-lupascu** [LegendApp/legend-state#45]
so on most of my react-native projects i use react-navigation and there is a need for 2 stacks that conditionally render based on the user being authenticated or not. the way i currently achieved this by doing:

```
const app = useSelector(() => ({
  initialized: store.app.initialized.get(),
  isInternetReachable: store.app.isInternetReachable.get(),
  isAuthenticated: store.isAuthenticated.get(),
}));

<NavigationContainer>
  <Stack.Navigator>
    {!app.initialized ? (
      <Stack.Screen
        name="Initial"
        component={InitialScreen}
      />
    ) : !app.isAuthenticated ? (
      <Stack.Screen
        name="SignIn"
        component={SignInScreen}
      />
    ) : (
      <>
        <Stack.Screen
          name="Home"
          component={HomeScreen}
        />
      </>
    )}
   </Stack.Navigator>
</NavigationContainer>
```

is there a better / recommended way of doing this?

**Comment by chakravarthi-bb** [comment]
Maybe you can utilize `Show` Component

**Comment by jmeistrich** [comment]
Unfortunately React-Navigation throws errors if children of `Stack.Navigator` are not `Stack.Screen`, so we can't use any other components there. So you could do it this way or make the whole component an `observer`, and then you wouldn't need the `useSelector`.
