### ISSUE TITLE
Inserting opaque objects

### ISSUE THREAD

**Issue by prbxr** [LegendApp/legend-state#46]
I would like to put fabric.Canvas in an observable.
#6

**Comment by jmeistrich** [comment]
I'm curious - what's the use case for that?

**Comment by jmeistrich** [comment]
@prbxr I added an `opaqueObject` helper in `0.21.6`.

```js
import { observable, opaqueObject } from '@legendapp/state'

const canvas = new fabric.Canvas()

const obs = observable({ text: 'hi', canvas: opaqueObject(canvas) })
```

This will make `canvas` work effectively as a primitive, so you can `obs.canvas.get()` and `obs.canvas.set(...)`. And changes within the canvas won't fire any change listeners.

How does that work for you?
