### ISSUE TITLE
Does it work with react-query?

### ISSUE THREAD

**Issue by kylegillen** [LegendApp/legend-state#48]
Hi. Great library! 

I saw your fetch example in the docs which uses the `useObservable` hook and fetch.
Any way to employ this with react-query's `useQuery` and other hooks?

**Comment by princed** [comment]
This is naive hook I've been using with [Urql](https://github.com/FormidableLabs/urql), and I'd be grateful for any feedback.

```tsx
import {
  beginBatch,
  endBatch,
  isObservable,
  mergeIntoObservable,
  Observable,
} from '@legendapp/state';
import { useObservable, useObserve } from '@legendapp/state/react';
import {
  AnyVariables,
  CombinedError,
  createRequest,
  OperationContext,
  RequestPolicy,
  TypedDocumentNode,
  useClient,
} from 'urql';
import { onEnd, pipe, subscribe } from 'wonka';

export type UseQueryState<Data> = {
  fetching: boolean;
  data?: Data;
  error?: CombinedError;
};

export type UseQueryResponse<Data, Variables extends AnyVariables> = [
  Observable<UseQueryState<Data>>,
  Observable<Variables>
];

export function useObservableQuery<Data, Variables extends AnyVariables>(args: {
  query: TypedDocumentNode<Data, Variables>;
  requestPolicy?: RequestPolicy;
  context?: Partial<OperationContext>;
  variables?: Variables;
  pause?: Observable<boolean> | boolean;
}): UseQueryResponse<Data, Variables> {
  const client = useClient();
  const response = useObservable<UseQueryState<Data>>({
    fetching: false,
    data: undefined,
    error: undefined,
  });
  const variables = useObservable<Variables>(args.variables);

  useObserve(() => {
    const pause = isObservable(args.pause) ? args.pause?.get() : args.pause;
    if (pause === true) {
      return;
    }

    const vars = variables.get() as Variables;
    const request = createRequest<Data, Variables>(args.query, vars);
    // executeQuery returns wonka stream (https://wonka.kitten.sh)
    const source = client.executeQuery(request, {
      requestPolicy: args.requestPolicy,
      ...args.context,
    });
    response.assign({ fetching: true });

    const subscription = pipe(
      source,
      onEnd(() => {
        response.assign({ fetching: false });
      }),
      subscribe(result => {
		// Not sure if that's the right way to update deeply nested fields
        beginBatch();
        response.assign({ fetching: false, error: result.error });
        mergeIntoObservable(response, {
          data: result.error ? undefined : result.data,
        });
        endBatch();
      })
    );

    return () => subscription.unsubscribe();
  });

  return [response, variables];
}
```

**Comment by princed** [comment]
One problem I'm having with it is that deeply nested fields that don't exist at the time of first render don't get observed and subsequently re-rendered after they merged into observable. 

Example:
```tsx
export const Example: FC = () => {
  const [response$] = useObservableQuery({ query: exampleDocument });

  // If the field doesn't exist when initially rendered, 
  // it won't get rendered when is added to the store  
  return (
    <>{response$.data.nested.field}</>
  );
};
```

**Comment by hckhanh** [comment]
> Hi. Great library!
> 
> I saw your fetch example in the docs which uses the `useObservable` hook and fetch. Any way to employ this with react-query's `useQuery` and other hooks?

This is my concern too
Most of data I need to process will come from react-query.

**Comment by princed** [comment]
@jmeistrich Thank you very much for the feedback!

> It should be able to infer the type there so the <Variables> should not be needed

> The `?.get()` should not be necessary

Great catch, those were some leftovers! 

> unless that's not working in TS strict mode or something?

Strict mode doesn't play well with Legend at all unfortunately, I spent some time trying to fix that, but eventually gave up.

> `mergeIntoObservable` is for merging deeply nested children, like if you wanted to merge the previous data together with the new data. But in this case I'm guessing the new data would overwrite the old data?

This actually the most interesting to me question at this stage. Yes, the new data is going to overwrite the old data, but if we do that, will it trigger changes all over the tree down from data, or only for the branches that are different? The documentation on `assign()` doesn't say much about it.

**Comment by jmeistrich** [comment]
@princed It will only trigger changes on branches that are different.

We will be improving strict mode support soon. There's some progress already in https://github.com/LegendApp/legend-state/issues/42

**Comment by jmeistrich** [comment]
We're working on adding a library of helpers and hooks, which will be in the next update. From there we can start adding more hooks like a react-query one. 

But I'm quite overwhelmed by the docs - react-query does a lot! Are you mainly interested in wrapping `useQuery` to return an observable, and to not trigger re-render on changes? Or can you describe more of how you'd want an observable wrapper for react-query to work?

**Comment by Manc** [comment]
Just a comment… I use React Query quite a bit. For the project I'm currently working on, I also used React Query, but since I switched to this Legend State library, I found myself abandoning React Query in more and more places.

My dilemma is this: In an app one usually wants to have a single source of truth for the data within the app. Using Legend State, that state becomes the single source of truth. However, React Query manages its own state and if you try to sync both states you're going to run into trouble.

So, let's say you fetch data from an API, use `onSuccess` to put fetched data into a Legend State ("LS") object. Then the user modifies the data. Then you would usually do a mutation to submit the data to the server. You could then manually update the state of the React Query ("RQ") query, which runs `onSuccess` and renders the components using the query and also overwrites the Legend State state. Depending what you're doing in your app, this can become really tricky, especially if the API data (what RQ would provide) and the app's state (what LS would be) are not of identical structure. At least this is what my problem was and I gradually replaced RQ queries with simpler `fetch` calls, but obviously I lost some advantages of RQ like automatic retry.

To be honest, I didn't give it too much thought whether there is a better solution, but boiling it down and realising that having two separate states with slightly different purposes that must be synchronised somehow, is not a good start.

**Comment by jmeistrich** [comment]
I think if we just want to read-only from React Query ("RQ") it would be pretty trivial to make a hook that puts fetched data into an observable, as @Manc said. It could be pretty easy to also support mutations - the hook could observe the LS observable for changes and handle the `useMutation` internally? Something like:

```js
function useQueryObservable(key, getFunction, postFunction) {}

// Used like
useQueryObservable(['todos'], () => axios.get('...'), (data) => axios.post('...', data))
```

Ideally a user of the LS hook should not have to worry about the RQ state, and LS would manage the sync between them? I'm just skimming over the docs at this point so I may be very wrong - I'll need to dig more into how RQ works and is used.

**Comment by jmeistrich** [comment]
There might also be some value in creating an LS hook that does some of the basics that people use RQ for? I just added a `useFetch` hook in `0.21.6` that just wraps around the lifecycle of the promise and exposes `{ data, error, loading }` as an observable, which works like this:

```jsx
const obsData = useFetch<{ fact: string }>('https://catfact.ninja/fact');

return <div>{obsData.data.fact}</div>
```

Maybe a hook with a few more features like retries and mutations could be a useful minimal alternative to RQ? Of course I'm definitely not trying to go too deep on that - RQ does a whole lot! But since we already have the local state and caching covered, it could be useful? If that seems like a good idea, let's start a new thread for it? I don't want to take this RQ thread too off topic.

**Comment by attiqeurrehman** [comment]
any idea on the timeline for the hook for react-query?

**Comment by jmeistrich** [comment]
I need more information before I can start on this. I can figure it out by reading docs/articles and watching videos but I don't have bandwidth for that at the moment (my immediate focus is on documentation and getting to 1.0). If you could help me with these things it would be super helpful:

1. What features of react-query would you want to be supported? Wrapping around `useQuery` should be pretty straightforward, and I think doing mutations on changes should be straightforward too. Would that be all you'd need? Or are there other things you'd need supported?
2. Code samples of how you'd like to use a `useObservableQuery` hook would be great - then I could build the hook to make your code work.
3. A PR would be great! Or if you want to put together an unfinished prototype, it would be a great starting point to finish it off.

**Comment by attiqeurrehman** [comment]
1. By creating wrapper around the useQuery and useMutation, we can complete most of our usecases. 
2 & 3. I can try working on some code sandbox and share it with you for some feedback.

**Comment by attiqeurrehman** [comment]
checkout [this](https://codesandbox.io/s/keen-glitter-s9h13q?file=/src/index.jsx) simple wrapper.

**Comment by jmeistrich** [comment]
Thanks @attiqeurrehman! 

I am working on a prototype now. It turned out that the hard thing to solve is changing the behavior of `userQuery` to not re-render the component. I have a prototype that seems to work, but requires a couple of changes to the core, so I'll test it some more tomorrow and post it here when it works.

**Comment by attiqeurrehman** [comment]
I don't know if it helps but react-query have an [observer](https://tanstack.com/query/v4/docs/reference/QueryObserver) for query as well.

**Comment by jmeistrich** [comment]
@attiqeurrehman That is very helpful, thanks!

**Comment by jmeistrich** [comment]
I have a prototype working in this [sandbox](https://codesandbox.io/s/legend-state-useobservablequery-0w1yil?file=/src/useObservableQuery.ts).

In the sandbox I have 3 examples:
1. Basic using `observer`: It re-renders whenever the query data changes, so it's basically equivalent to `useQuery`.
2. Optimized using `Switch` and `Show`: The individual elements re-render themselves whenever their data changes and the component itself only renders once.
3. Mutating: Give it a mutationFn and it will call `mutate` whenever the observable is changed. Try clicking the "Change email" button to modify the observable and see the API result from it (using the https://reqres.in/ endpoints).

I tried a few different ways to do it. The other most promising option was wrapping around the `useQuery` function and overriding `observer.getCurrentResult` to make the `useSyncExternalStore` not trigger re-render. But that broke react-query-devtools. So the solution I ended up with is to basically just copy the whole source of the `useBaseQuery` hook but replace the `useSyncExternalStore` part with the observable things, and that appears to work quite well. The downside is it's more code and would need to be updated as React-Query changes their `useBaseQuery` hook to keep up with it. If anybody has ideas to make wrapping around useQuery while disabling re-renders work, I would love to hear them!

Let me know what you think of this? It seems to work pretty well now. I'd just want to add all the overrides they have for different numbers of parameters before fully releasing it.

**Comment by jmeistrich** [comment]
I added the a `useObservableQuery` hook in `0.21.11`. Use it like this:

```js
import { useObservableQuery } from '@legendapp/state/react-hooks/useObservableQuery'

const obs = useObservableQuery(
    {
        queryKey: ["mutatingData"],
        queryFn: () =>
        axios.get("https://reqres.in/api/users/2").then((res) => res.data.data),
    },
    {
        mutationFn: (newData) =>
        axios
            .post("https://reqres.in/api/users/2", newData)
            .then((res) =>
                mutateResult.set(`Mutated: ${JSON.stringify(res, null, 4)}`)
            ),

    }
);
```

I'll add more details to the documentation site soon.

Let me know how that works for you? Is it missing anything?

**Comment by nextriot** [comment]
This looks great! Any chance of making one of these for `infiniteQuery`? 
https://tanstack.com/query/v4/docs/guides/infinite-queries

**Comment by jmeistrich** [comment]
FYI this hook was a bit unstable in some configurations but seems pretty solid in `0.21.16`. And there's now an example on the docs page: https://legendapp.com/open-source/state/react-examples/#auto-saving-form

Please let me know if you find any issues with it.

**Comment by jmeistrich** [comment]
There is now a good TanStack Query plugin in v3: https://legendapp.com/open-source/state/v3/sync/tanstack-query/

And the core sync system now covers a lot of the use case for Query so it may not even be needed anymore: https://legendapp.com/open-source/state/v3/sync/persist-sync/

So I’m going to close this issue. But please let me know if it’s not quite good enough.

**Comment by forabi** [comment]
is there a way to track the progress of the queryFn call? looks like it does not work when wrapped with `syncState()`
