### ISSUE TITLE
React test is failing

### ISSUE THREAD

**Issue by Manc** [LegendApp/legend-state#55]
Just a quick note, you may have already noticed this: one test in `react.test.ts` is failing.

**Comment by Manc** [comment]
Also, the import from `src/` at the top of this file doesn't work for me.

```
import { persistObservable } from 'src/persist/persistObservable'; // 👎
import { persistObservable } from '../persist/persistObservable'; // 👍
``

**Comment by jmeistrich** [comment]
Ah yes, thanks! I always run tests before a release but I should make sure to do that before pushing changes in progress to github late at night 😂
