### ISSUE TITLE
Add ability to use multiple instances of MMKV in persistObservable

### ISSUE THREAD

**Issue by SMhdAsadi** [LegendApp/legend-state#57]
With current implementation, only one instance of storage for MMKV is used. MMKV supports [multiple instances](https://github.com/mrousavy/react-native-mmkv#create-a-new-instance). It would be awesome to add this capability to persistObservable function.

**Comment by jmeistrich** [comment]
I just added this in the latest commit but it's very late so I'll wait until tomorrow to release an update.

**Comment by jmeistrich** [comment]
Added in `0.21.11`.
