### ISSUE TITLE
Render count is high with useObservableReducer

### ISSUE THREAD

**Issue by attiqeurrehman** [LegendApp/legend-state#58]
Hi,

I have tried your [example ](https://codesandbox.io/s/github/attiqeurrehman/legend-state-tasks-with-reducer)of using observable with reducer but the render count is still high as compared to using it directly with [API](https://codesandbox.io/s/vigorous-zhukovsky-m35t82). 

Maybe I am missing here something?

**Comment by jmeistrich** [comment]
@attiqeurrehman That first example doesn't seem to use legend-state at all? Do you have a different codesandbox that uses `useObservableReducer`?

**Comment by attiqeurrehman** [comment]
Thanks I have fixed the link.

**Comment by jmeistrich** [comment]
This line makes App re-render every time `observableTasks` changes:

```js
const tasks = observableTasks.get();
```

So you'd want a mixture of your examples, where you pass the observable down to TaskList and use `For` to render it. I made a couple tweaks to do that: https://codesandbox.io/s/great-austin-yr0bbh?file=/src/App.js

However it doesn't seem to update when editing. I'm not very familiar with the reducer pattern so it may need something else for `onChange` to work correctly? Or is that a bug in the hook that needs fixing?

I'm curious - what is the benefit for you of managing the task list with a reducer vs. setting observables directly? It seems to add a lot of extra complexity and makes it slower (creating a whole new tasks array on every change). I never got into the reducer/redux pattern so I think I never learned the benefits.

**Comment by attiqeurrehman** [comment]
Thanks for pointing it out. I will check out the `onChange` and let you know. 

Since we already have a running application and I am just exploring if observable can be used and how much effort it will be so if it's just decorating the reducer or components it's fairly easy and very little effort. Reducer/ redux is easy to grasp in the sense that logic is moved to outside react components and making it easier to understand/ read the code. Plus the ability to add middleware e.g. logging is a very nice touch. 

P.S: That's just my opinion on reducer/redux and my knowledge is also very little on it.

**Comment by jmeistrich** [comment]
That's a great reason!
