### ISSUE TITLE
Cannot `set` in `useEffect`

### ISSUE THREAD

**Issue by hckhanh** [LegendApp/legend-state#62]
When I upgraded from `0.21.8` to `0.21.10`, everything is not going to work, I have many logic that set the legend's state inside `useEffect`.
Since my logic is connected to other source of state outside legend's state
https://codesandbox.io/s/modern-firefly-oup5hk?file=/src/App.js

**Comment by jmeistrich** [comment]
I'm confused - the example looks like it's working? What is the problem you're seeing?

**Comment by hckhanh** [comment]
Maybe My PC has a problem, I saw it did not count in this morning. Well 😞

**Comment by pavelrotek** [comment]
Hi jay, i just tried Khanh´s example on my mobile phone and see double increment. 

https://user-images.githubusercontent.com/20819654/199902331-2d23b857-e334-46bb-a5b7-352f85375fb3.MOV

Do you think it has something to do with react 18 double rerender in dev mode? Maybe there should be some react 18 gotchas section in legend-app docs

Pavel

**Comment by jmeistrich** [comment]
@pavelrotek Yes, I'm pretty sure that's what it is, because it starts a setInterval in useEffect which runs twice in dev mode.
