### ISSUE TITLE
Auto import doesn't work in VS Code

### ISSUE THREAD

**Issue by SMhdAsadi** [LegendApp/legend-state#68]
Every time we should type imports by hand and VS Code doesn't help us with imports.
Is this a problem with library or VS Code? I tested this in several computers and none of them work.

**Comment by jmeistrich** [comment]
I've noticed that too - I thought it was my VSCode. If it's a problem with the library I have no idea what it could be, but I'll look into it. And if anyone knows how to solve it, I would appreciate the help :)

**Comment by SMhdAsadi** [comment]
Oh yes you're right. This project is using a monorepo somehow. I close this issue since it is working fine in a normal project.
