### ISSUE TITLE
<For /> does not re-render if array length does not change in non-optimized mode

### ISSUE THREAD

**Issue by joakimbeng** [LegendApp/legend-state#71]
Hi and thanks for a great library!

I am experiencing an issue with `<For />` and filtered arrays in non-optimized mode, apparently it doesn't re-render if the array length is not changed.

Here's a sandbox that reproduces the bug: https://codesandbox.io/s/legend-w-observable-forked-cegnon?file=/src/App.tsx

In the sandbox changing the category in the dropdown from "One" -> "Two" -> "Three" -> "Four" works as intended but if one changes from "One" -> "Three" (as their results have the same length) it's still category "One" that is rendered.

**Comment by jmeistrich** [comment]
Oh that's no good! I'll look into that tomorrow.

**Comment by jmeistrich** [comment]
This should be fixed in `0.22.3`. But please let me know if it's still not working right.

**Comment by joakimbeng** [comment]
> This should be fixed in `0.22.3`. But please let me know if it's still not working right.

Yes, it works! Thank you for the quick fix 😃
