### ISSUE TITLE
Legend-State for vanilla JS

### ISSUE THREAD

**Issue by mkvillalobos** [LegendApp/legend-state#73]
Hi!  Great library!!

In the library documentation, is indicated that Legend-State was designed to be cross-platform, but you begin with React first!  

Would be great if you can make Legend-State work with vanilla JS also!  

Please, keep your good work!  Thank you for this great library!

Best regards

**Comment by jmeistrich** [comment]
What kinds of features are you looking for in vanilla JS support? All of the core functionality (everything not under React on https://legendapp.com/open-source/state/) works in vanilla JS or any library. Is there something else that would help your use case?

**Comment by jmeistrich** [comment]
I'm going to close this due to no reponse, but please let me know if there's anything that would help and we can reopen it.
