### ISSUE TITLE
React Native helper components

### ISSUE THREAD

**Issue by matthewmturner** [LegendApp/legend-state#76]
I see in the blog there are mentions of React helper components such as `Computed`, `Show`, `Switch`, and `For` but i dont see any mention of these for react native.  Can you provide insight on this and if there are helpers for React Native?

**Comment by jmeistrich** [comment]
These components aren't web or native specific, so they work in all React platforms - React (DOM) and React Native.

**Comment by matthewmturner** [comment]
@jmeistrich cool! does that apply to everything in the React section of docs?  Is there anything thats React specific? Or any differences in how to use between React and React Native?

**Comment by jmeistrich** [comment]
Yes, that applies to all the basics and fine-grained reactivity features. There's a different set of reactive components, and some of the included hooks are web only (but we can add more react native hooks). Generally the docs should specify whether they're web or react native, and if not specified it works on both. But let me know if any of that is wrong or missing 😅
