### ISSUE TITLE
Create Slack / Discord community?

### ISSUE THREAD

**Issue by matthewmturner** [LegendApp/legend-state#77]
What do you think about creating a Slack or Discord channel to start building a community around Legend State / Motion? I'm hoping to start using this soon and would be great to have a place to have more informal conversations.

**Comment by chakrihacker** [comment]
I vote for slack

**Comment by matthewmturner** [comment]
Slack is also my preference

**Comment by jmeistrich** [comment]
Why do you prefer Slack over Discord? I had the impression that Discord is more favorable these days, especially for developer communities?

**Comment by matthewmturner** [comment]
I prefer slack for three main reasons. 

First, which is community related, is that there was a poll by Jamon where he was looking to move the React Native Slack community to Discord and The community overwhelmingly voted for Slack. You can read that thread for more arguments for / against each.

![image](https://user-images.githubusercontent.com/22136083/210237736-3d8221cd-99e1-4251-a217-2114d1066473.jpeg)

But a counter point to that is that there are React Native and Expo communities both on Discord. I know Legend can be used with React as well but I'm not involved in those communities so not sure where most of them are.

The second reason is that I prefer Slacks approach to message threads over Discord. 

The third reason is more personal, more of what I do on a day to day basis is in Slack - it's closer to where I work which makes it convenient and maybe that will be the case for others since I'm not sure how many people use Discord for work. 

To be honest, it's not clear to me that one is more popular than the other for dev communities. I would be totally fine with either. Just looking forward to having a place to chat.

**Comment by jmeistrich** [comment]
Those are good reasons that I agree with :).

I made a Slack community: https://join.slack.com/t/legendappcommunity/shared_invite/zt-1mfjknpna-vUL2s1qOuNeZL12~t2RruQ
