### ISSUE TITLE
enableLegendStateReact is amazing

### ISSUE THREAD

**Issue by stephenh** [LegendApp/legend-state#8]
I was just checking in on legend-state, and saw the new `observer`-less/`useComputed`-less React integration. Like, lol, wat? That's super neat.

My understanding is that, by hooking into this setter, you're basically getting react to give you a "beginRender" and "endRender" API, which lets you wrap every React component with the equivalent of the `observer` HOC behavior.

Does that sound right?

If so, I wonder if a small TLDR of that might be useful in the docs and/or source, just as a hint to others who will wonder the same "wtf does this even work?" and potentially not trust it until they understand (e.g. I thought maybe it'd require the babel plugin or something like that).

I have conflicting emotions; this is even more amazing to get SolidJS-style brevity/reactivity in React, but I don't know I'd bet/couple a large codebase to something that might break in React 19/20/etc. I suppose the worst case scenario would be to go back and add `observer` HOCs to components. That wouldn't be terrible.

I wonder if the React team would be open to this sort of `beginRender` / `endRender` API. Or almost like `render` middleware. I imagine surely they've been asked this before, multiple times, and said no, so :shrug: .

But anyway, this is not an issue, just wanted to call out how amazing this is. Great work!

**Comment by jmeistrich** [comment]
Yes exactly, it's hooking into `ReactCurrentDispatcher.current` changing in React's internals to detect when render begins/ends. I didn't even know it was possible until I saw Preact Signals: https://github.com/preactjs/signals/blob/main/packages/react/src/index.ts

That's a great idea to describe it more in the docs - will do that soon!

This is so deep in the React internals that it seems very unlikely that it would change completely, but I'll stay on top of alpha versions to make sure it's still working. And I'm keeping in contact with the Preact team who has a similar implementation, so if there ever is an issue we could help each other. I think it would be worth discussing with the React team to enable libraries like this to work in a more officially supported way. I'll look into that 👍.

Thank you for the comment! ❤️

**Comment by jmeistrich** [comment]
(Leaving open until I update the docs)

**Comment by stephenh** [comment]
> This is so deep in the React internals that it seems very unlikely that it would change completely

Yeah, that's a good point.

Also great to see that Preact is using the same approach, both in terms of sharing ideas on how to keep it working in future Reacts, but also hopefully brings more weight to convincing the React team that some sort of API to help 3rd-party frameworks more seamlessly/succinctly bridge the gap from observers (or whatever state idiom the library is using) into React's hooks-only world would be worth supporting. :crossed_fingers:

**Comment by jmeistrich** [comment]
> I think I have basically convinced myself that "just add `observers`s around everything" would be a sufficient fallback/mitigation, just in case it did end up not working in future Reacts, to make it worth using/betting on today.

Yes, I agree with that. If in the worst case future there is no way to hook into the lifecycle in a similar way, `observer` would always be a reasonable fallback.

**Comment by jmeistrich** [comment]
I added some documentation about how it works to https://legendapp.com/open-source/state/react-basics/#enablelegendstatereact. Do you think that's good or is there anything I didn't comment well?

**Comment by stephenh** [comment]
That's great! Thanks!
