### ISSUE TITLE
Setup GitHub Actions to run on pull requests

### ISSUE THREAD

**Issue by matthewmturner** [LegendApp/legend-state#80]
I noticed while working on https://github.com/LegendApp/legend-state/pull/79 that GitHub actions isnt setup yet.  I think getting this setup would add a lot of value by making it easier for others to contribute.  I think to start just running the test suite and formatting / linting checks would be good.

I can work on this if you agree it would be useful.

**Comment by jmeistrich** [comment]
Yes, that would be great!
