### ISSUE TITLE
react-native-web support?

### ISSUE THREAD

**Issue by djMax** [LegendApp/legend-state#89]
I am futzing around with Expo and react-native-web for a simple project, but it seems legendapp causes some problems for react-native-web which I don't understand. Basically I just have an observable:

```
import { observable } from "@legendapp/state"

export const GameState = observable({
  myMove: true,
});
```

And then in a component:

```
import { observer } from "@legendapp/state/react";
export const GameScreen = observer(() => {
// Stuff
});
```

But on load, it fires a number of errors:

```
react.mjs:191 Uncaught TypeError: undefined is not a function
    at ./node_modules/@legendapp/state/react.mjs (react.mjs:191:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./src/screens/GameScreen.tsx (GameScreen.tsx:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./App.tsx (bootstrap:856:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at ./node_modules/expo/AppEntry.js (AppEntry.js:1:1)
    at __webpack_require__ (bootstrap:789:1)
    at fn (bootstrap:100:1)
    at 1 (index.tsx:9:1)
    at __webpack_require__ (bootstrap:789:1)
    at bootstrap:856:1
    at bootstrap:856:1

/node_modules/@legendapp/state/react.mjs
Can't import the named export 'Children' from non EcmaScript module (only default export is available)
console.<computed> @ index.js:1
handleErrors @ webpackHotDevClient.js:174
./node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:213

```

**Comment by jmeistrich** [comment]
It seems like it's a problem with your bundler and ESM modules? It's erroring when trying to import from React. Can you share a project to test?

I searched for that error (Can't import the named export 'Children' from non EcmaScript module) and found a lot of results - this looks promising: 
https://stackoverflow.com/questions/71054449/cant-import-the-named-export-directive-from-non-ecmascript-module-only-defau

**Comment by djMax** [comment]
I agree it's something to do with stupid ESM which is the bane of everything Javascript, BUT I'm not sure why legend-state is tickling it yet. I've rolled back to a previous version of the project before adding state and it renders fine, so I'm walking forward now to see where it fails and then will try to make a minimal repro. It's basically just an expo project + typescript.

**Comment by djMax** [comment]
```
const Hello = observer(() => (
  <Text>{obs.text.get()}</Text>
));
```
So it is the call to observer() that triggers it. Importing the module is fine, creating an observable is fine, but as soon as I call observer, it blows up.

**Comment by jmeistrich** [comment]
I think that would be because it doesn't actually run the /react import until you use something from it? If so then calling `enableLegendStateReact()` for example should also cause the error?

**Comment by djMax** [comment]
Ok, so this line in the MJS:

```
import { useReducer, useRef, forwardRef, memo, useCallback, createElement, Children, useMemo, useEffect } from 'react';
```

fails, because the import of 'react' ends up with an object with "default" on it, and all the desired symbols hang off that. I wonder if this is a tsconfig thing...

**Comment by djMax** [comment]
Remapping all the exports in the package to the js version instead of the mjs version fixes it, but I don't get why legend state is special.

**Comment by jmeistrich** [comment]
It's possible the package's exports are not set up exactly right - it's very hard to figure out the *correct* way to export all the different flavors. It's worked well in every environment I've tested though? If you (or someone) knows how to set up the exports better I would be very happy to fix it.

**Comment by djMax** [comment]
Yeah, ESM is evil. Jest, react-native, Typescript, Node vx/y/z... They all have different opinions about what magic spells you must cast.

**Comment by djMax** [comment]
https://github.com/djMax/legend-esm-expo

No typescript needed. Fails on vanilla expo + react-native-web.

**Comment by GiFarina** [comment]
webpack.config.js
```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);
  // Customize the config before returning it.
  config.module.rules.push(
    {
      test: /\.mjs$/,
      include: /node_modules/,
      type: 'javascript/auto',
    },
  );

  return config;
};

```

**Comment by djMax** [comment]
Workaround/config (which perhaps is the right way and not a workaround) fixes the web bundle. Here's what it built!

[ε Chess](https://chess.pyralis.com)

**Comment by jmeistrich** [comment]
@djMax Great! I'm happy to know that worked!

I tried to play but tapping on the board doesn't seem to do anything?

**Comment by djMax** [comment]
Should be fixed now - the dangers of continuous deployment on personal projects with few tests. :)

**Comment by jmeistrich** [comment]
Cool, the fractional moves are an interesting mechanic!
