### ISSUE TITLE
Typescript Inference is not working in Show component

### ISSUE THREAD

**Issue by SMhdAsadi** [LegendApp/legend-state#92]
Show component is awesome in the way that it can replace ugly conditional rendering. But it has one big downside.

When I use Show component for cases like 'render if some value is available', in the body of Show typescript says value can be undefined.

For example:
```tsx
interface PropTypes {
    value?: string;
}
// ...
<Show if={() => props.value}>
    <CustomComponent value={props.value} /> // props.value is possibly undefined
</Show>
```

Is it possible to tell typescript it is not undefined?

**Comment by jmeistrich** [comment]
I think this is a problem with the CustomComponent, not with Show. CustomComponent would also need to have value optional with `value?: string` in its props if you're using strict mode. Can you share the props interface for CustomComponent too?

**Comment by SMhdAsadi** [comment]
Yeah CustomComponent has a required prop named value.
But my point is that in the body of Show, we are sure that props.value is not undefined, right?

I can use props.value this way without typescript error:
```tsx
{props.value && (
    <CustomComponent value={props.value} />
)}
```
But in Show this is not the same. I should change all other places to be able to use Show.

Is it possible to infer that props.value is not undefined?

**Comment by jmeistrich** [comment]
Oh I see! I don't think it's possible for TypeScript to know that `value` is defined based on the selector passed to a component's props. If anybody knows how to do that I would be very happy to support it! But as far as I know it's not possible.
