### ISSUE TITLE
Add "then" prop to Show component

### ISSUE THREAD

**Issue by SMhdAsadi** [LegendApp/legend-state#93]
It is weird that `else` clause is above `then` in Show component. I think it is more readable to add a `then` prop to Show component and we can then use it above else prop.

e.x.
```tsx
<Show 
    if={...}
    then={ComponentA}
    else={ComponentB}
/>
```

**Comment by jmeistrich** [comment]
I see your point, but I think using children for rendering is the most intuitive way to use `Show`. The API is similar to [React's Suspense](https://17.reactjs.org/docs/concurrent-mode-suspense.html) and [Solid's Show component](https://www.solidjs.com/docs/latest/api#show), except that they use `fallback` whereas we liked the pairing of `if` / `else`. And I think it would be confusing to add an alternative `then` prop when children is the best option.

But please let me know if I'm looking at this the wrong way :)
