### ISSUE TITLE
`id` property when using `For` for component causes typescript error if not primitive

### ISSUE THREAD

**Issue by matthewmturner** [LegendApp/legend-state#95]
See conversation [here](https://legendappcommunity.slack.com/archives/C04HL57AXSM/p1675548822303089) for context.

The `For` component uses the `id` property for the provided objects if available which it expects to be a `number` or `string`.  However in my case its an object `id: {uuid: string}`.  This causes typescript to complain.

**Comment by jmeistrich** [comment]
@matthewmturner Sorry, I haven't had a chance yet. I've been focusing on finishing migrating Legend to use Legend-State for its sync system (see the persist branch) and finding issues running it in production with large amounts of data. That seems just about done now, and then I will try to solve as many of the open issues as I can before we go for 1.0.

**Comment by matthewmturner** [comment]
Hi there - just checking in on this.  I believe error is bubbling up to the browser too which i suppose makes sense.  Let me know if i'm off here.
 
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/22136083/229265205-061ddd57-a749-4c24-a4c0-f8fc2390e3a5.png">

**Comment by matthewmturner** [comment]
@jmeistrich could this also cause bugs?  im having issues with a `For` component where its not rendering the right number of items.  Specifically i have a computed observable that changes based on a user selected filter value.  ive verified that the computed observable returns the right items / item count but `For` ends up rendering way too many items.  After i filter a couple times it just keeps adding to the rendered output (for example, the computed observable only has 10 items but i end up seeing like 40).

This is on the latest release candidate(29)

**Comment by matthewmturner** [comment]
Oh i think it may be the duplicate key issue since one of my objects has id but its an object not number / string

**Comment by matthewmturner** [comment]
would it be possible to add a `keyExtractor` prop to `For`? Same as `FlatList` (https://reactnative.dev/docs/flatlist#keyextractor)

**Comment by matthewmturner** [comment]
Switching to `FlatList` for now, let me know if you agree `keyExtractor` makes sense.  If I have time I can try to work on that but I confess I've been short of spare time lately so cant guarantee I'll be able to.

**Comment by jmeistrich** [comment]
It's unfortunately tougher than just a `keyExtractor` because the core uses the id field to optimize for elements being rearranged in the array. I've been debating whether that complexity is even worth it to optimize an edge case, and it may be that if I revisit it I can find a simpler way to do it. I'll try to figure it out soon.

**Comment by matthewmturner** [comment]
ah yes i remember you mentioning that when we first discussed this.  so you do think it may be possible to keep the optimization and have `keyExtractor` type functionality?

**Comment by jmeistrich** [comment]
I'm not sure, I think we'd have to put the keyExtractor on the observable itself somehow.

**Comment by jmeistrich** [comment]
I added a keyExtractor option which I think should solve this for you. It needs to go into the data structure itself, just named as `${variable}_keyExtractor`. For example:

```js
const data = observable({
    arr: [],
    arr_keyExtractor: (item) => item.id.uuid
})
```

Then that should work correctly in the core and `For` will pick it up too. Please let me know if that works for you?

**Comment by matthewmturner** [comment]
@jmeistrich I had actually switched to flat list so not using For now. But I'll try to give it a test. I think I'm okay with that API though. Appreciate you fixing that.
