### ISSUE TITLE
computed returning an array is not updating dom

### ISSUE THREAD

**Issue by ps73** [LegendApp/legend-state#99]
It seems that tracking an array inside computed is not updating dom. Is this intended or is it a bug?

Example:
https://codesandbox.io/s/sandpack-project-forked-dlvuex?file=/App.js

**Comment by jmeistrich** [comment]
It's a bug, because I had expected computed to always return a new object. But since this observable returns an existing array it's breaking all the checks for `current !== previous`. I'll try to get a fix out asap.

**Comment by jmeistrich** [comment]
For now if you clone the array it will work properly:

`const allMessages = computed(() => messages.get().slice());`

**Comment by robknight** [comment]
I have a (possibly?) related issue. I have an object graph representing a tree structure, which is stored in an observable. For display, I want to flatten this into an array, using a computed. To flatten the tree into an array, I'm using Array.from with a generator function and wrapping this in useComputed(). However, although components can track updates to the underlying object graph, these do not seem to propagate via the computed. I can verify that the computed function is being re-run, but the result does not seem to cause a DOM update.

Here's a sandbox:

https://codesandbox.io/s/elated-alex-7p43p4?file=%2Fsrc%2FApp.tsx

I can see that the computed re-runs after clicking the button, and does return a new result, which is not equal to the previously-returned result (it is not the same array, nor are the contents the same). However, this doesn't cause any change in the <For> component.

It's possible that I'm making a silly mistake, but if so I can't see it!

**Comment by jmeistrich** [comment]
That does appear to be the same issue. The Array.from returns a new array object, but it contains the same Nodes, so because `current === previous` for each element in the array it's not notifying the listeners in the computed. I'll try to figure out a good solution to this soon.

**Comment by jmeistrich** [comment]
I believe this is fixed now so I’m going to close it, but please let me know if it’s still an issue.
